# Generated by Django 5.2.7 on 2025-12-24 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaxSubEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ma_tieu_muc",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Mã tiểu mục"
                    ),
                ),
                (
                    "ten_tieu_muc",
                    models.TextField(verbose_name="Tên gọi (Nội dung kinh tế)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
            ],
            options={
                "verbose_name": "Tiểu mục thuế",
                "verbose_name_plural": "Danh mục Tiểu mục thuế",
                "ordering": ["ma_tieu_muc"],
            },
        ),
        migrations.CreateModel(
            name="TaxLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tinh",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Tỉnh/Thành phố"
                    ),
                ),
                (
                    "co_quan_thue_group",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="Cơ quan thuế"
                    ),
                ),
                (
                    "xa_phuong",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Xã/Phường"
                    ),
                ),
                (
                    "ma_co_quan_thu",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Mã cơ quan thu"
                    ),
                ),
                ("ten_co_quan_thu", models.TextField(verbose_name="Tên cơ quan thu")),
                (
                    "kho_bac",
                    models.CharField(
                        max_length=200, verbose_name="Kho bạc nhà nước (KBNN)"
                    ),
                ),
                (
                    "ma_dia_ban",
                    models.CharField(max_length=50, verbose_name="Mã địa bàn"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
            ],
            options={
                "verbose_name": "Cơ quan thu",
                "verbose_name_plural": "Danh mục Cơ quan thu",
                "ordering": ["tinh", "co_quan_thue_group", "xa_phuong"],
                "indexes": [
                    models.Index(
                        fields=["tinh", "co_quan_thue_group", "xa_phuong"],
                        name="tax_payment_tinh_844fb9_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TaxPaymentStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten_nguoi_nop",
                    models.CharField(max_length=200, verbose_name="Tên người nộp thuế"),
                ),
                (
                    "ma_so_thue",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Mã số thuế"
                    ),
                ),
                ("dia_chi", models.TextField(blank=True, verbose_name="Địa chỉ")),
                ("ngay_lap", models.DateField(verbose_name="Ngày lập bảng kê")),
                (
                    "tong_so_tien",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Tổng số tiền",
                    ),
                ),
                (
                    "exported_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="tax_statements/",
                        verbose_name="File đã xuất",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "tax_location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tax_payment.taxlocation",
                        verbose_name="Cơ quan thu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bảng kê nộp thuế",
                "verbose_name_plural": "Danh sách Bảng kê nộp thuế",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaxPaymentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ma_tieu_muc",
                    models.CharField(max_length=50, verbose_name="Mã tiểu mục"),
                ),
                ("noi_dung", models.TextField(verbose_name="Nội dung")),
                (
                    "so_tien",
                    models.DecimalField(
                        decimal_places=0, max_digits=15, verbose_name="Số tiền"
                    ),
                ),
                ("stt", models.IntegerField(default=1, verbose_name="STT")),
                (
                    "statement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="tax_payment.taxpaymentstatement",
                        verbose_name="Bảng kê",
                    ),
                ),
                (
                    "tax_sub_entry",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tax_payment.taxsubentry",
                        verbose_name="Tiểu mục",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dòng tiểu mục",
                "verbose_name_plural": "Các dòng tiểu mục",
                "ordering": ["stt"],
            },
        ),
    ]
