# Generated by Django 5.2.7 on 2025-12-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tax_payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxpaymentstatement",
            name="nguoi_nop_thay",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Người nộp thay"
            ),
        ),
    ]
