# Generated by Django 5.2.7 on 2025-12-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tax_payment", "0002_taxpaymentstatement_nguoi_nop_thay"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxpaymentstatement",
            name="dia_chi_nguoi_nop_thay",
            field=models.TextField(blank=True, verbose_name="Địa chỉ người nộp thay"),
        ),
    ]
