# Generated by Django 5.2.7 on 2025-12-26 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tax_payment", "0003_taxpaymentstatement_dia_chi_nguoi_nop_thay"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxpaymentitem",
            name="ky_nop_thue",
            field=models.CharField(
                blank=True, max_length=7, verbose_name="Kỳ nộp thuế (mm/yyyy)"
            ),
        ),
    ]
