# Generated by Django 5.2.7 on 2025-12-28 17:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConversionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Mã định danh nghiệp vụ",
                        max_length=50,
                        verbose_name="Mã nghiệp vụ",
                    ),
                ),
                (
                    "debit_account_pattern",
                    models.CharField(
                        help_text="Tài khoản Nợ hoặc đầu mã (ví dụ: 1011, 101)",
                        max_length=100,
                        verbose_name="Mẫu tài khoản Nợ",
                    ),
                ),
                (
                    "credit_account_pattern",
                    models.CharField(
                        help_text="Tài khoản Có hoặc đầu mã (ví dụ: 3591, 359)",
                        max_length=100,
                        verbose_name="Mẫu tài khoản Có",
                    ),
                ),
                (
                    "score_1",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="HESOQUAY1 - Điểm số cho loại giao dịch này",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Hệ số quy đổi 1",
                    ),
                ),
                (
                    "score_2",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="HESOQUAY2 - Điểm số phụ (nếu có)",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Hệ số quy đổi 2",
                    ),
                ),
                (
                    "formula",
                    models.TextField(
                        blank=True,
                        help_text="CONGTHUC - Logic bổ sung (ví dụ: LEFT(TKCO,3)=[359])",
                        null=True,
                        verbose_name="Công thức bổ sung",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Ghi chú về loại nghiệp vụ này",
                        verbose_name="Mô tả nghiệp vụ",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Quy tắc này có được áp dụng không",
                        verbose_name="Đang kích hoạt",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
            ],
            options={
                "verbose_name": "Quy tắc quy đổi",
                "verbose_name_plural": "Quy tắc quy đổi",
                "ordering": ["code"],
                "indexes": [
                    models.Index(
                        fields=["debit_account_pattern", "credit_account_pattern"],
                        name="kpi_tool_co_debit_a_018d42_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="kpi_tool_co_is_acti_347cdf_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TellerTransactionBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "teller_id",
                    models.CharField(
                        help_text="User ID từ tên file (ví dụ: GRATHIEU)",
                        max_length=50,
                        verbose_name="Mã giao dịch viên",
                    ),
                ),
                (
                    "teller_name",
                    models.CharField(
                        help_text="Tên đầy đủ của giao dịch viên",
                        max_length=200,
                        verbose_name="Tên giao dịch viên",
                    ),
                ),
                (
                    "month",
                    models.IntegerField(
                        help_text="Tháng báo cáo (1-12)", verbose_name="Tháng"
                    ),
                ),
                (
                    "year",
                    models.IntegerField(help_text="Năm báo cáo", verbose_name="Năm"),
                ),
                (
                    "file_date",
                    models.DateField(
                        help_text="Ngày tháng từ tên file (DDMMYYYY)",
                        verbose_name="Ngày file",
                    ),
                ),
                (
                    "total_transactions",
                    models.IntegerField(
                        default=0,
                        help_text="Số lượng bút toán được xử lý",
                        verbose_name="Tổng số giao dịch",
                    ),
                ),
                (
                    "total_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tổng điểm quy đổi trong kỳ",
                        max_digits=15,
                        verbose_name="Tổng điểm quy đổi",
                    ),
                ),
                (
                    "matched_transactions",
                    models.IntegerField(
                        default=0,
                        help_text="Số giao dịch khớp với quy tắc",
                        verbose_name="Số giao dịch khớp",
                    ),
                ),
                (
                    "unmatched_transactions",
                    models.IntegerField(
                        default=0,
                        help_text="Số giao dịch không khớp quy tắc",
                        verbose_name="Số giao dịch không khớp",
                    ),
                ),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("processing", "Đang xử lý"),
                            ("completed", "Hoàn thành"),
                            ("error", "Có lỗi"),
                        ],
                        default="processing",
                        max_length=20,
                        verbose_name="Trạng thái xử lý",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Thông báo lỗi"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
            ],
            options={
                "verbose_name": "Lô giao dịch",
                "verbose_name_plural": "Lô giao dịch",
                "ordering": ["-year", "-month", "-file_date"],
                "indexes": [
                    models.Index(
                        fields=["teller_id", "year", "month"],
                        name="kpi_tool_te_teller__e93102_idx",
                    ),
                    models.Index(
                        fields=["processing_status"],
                        name="kpi_tool_te_process_35bc0e_idx",
                    ),
                ],
                "unique_together": {("teller_id", "file_date")},
            },
        ),
        migrations.CreateModel(
            name="TellerTransactionDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_no",
                    models.CharField(
                        help_text="REFNO - Số gom nhóm bút toán Nợ/Có",
                        max_length=50,
                        verbose_name="Số tham chiếu",
                    ),
                ),
                (
                    "transaction_date",
                    models.DateField(
                        help_text="Ngày thực hiện giao dịch",
                        verbose_name="Ngày giao dịch",
                    ),
                ),
                (
                    "transaction_time",
                    models.TimeField(
                        blank=True,
                        help_text="TRTIME - Thời gian giao dịch",
                        null=True,
                        verbose_name="Giờ giao dịch",
                    ),
                ),
                (
                    "debit_account",
                    models.CharField(
                        help_text="ACCTCD khi TRDRCR='D'",
                        max_length=50,
                        verbose_name="Tài khoản Nợ",
                    ),
                ),
                (
                    "credit_account",
                    models.CharField(
                        help_text="ACCTCD khi TRDRCR='C'",
                        max_length=50,
                        verbose_name="Tài khoản Có",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="TRAMT - Số tiền giao dịch",
                        max_digits=18,
                        verbose_name="Số tiền",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Điểm số được tính cho giao dịch này",
                        max_digits=10,
                        verbose_name="Điểm quy đổi",
                    ),
                ),
                (
                    "is_matched",
                    models.BooleanField(
                        default=False,
                        help_text="Giao dịch có khớp với quy tắc nào không",
                        verbose_name="Đã khớp quy tắc",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Ghi chú bổ sung về giao dịch",
                        verbose_name="Ghi chú",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="kpi_tool.tellertransactionbatch",
                        verbose_name="Lô giao dịch",
                    ),
                ),
                (
                    "matched_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="kpi_tool.conversionrule",
                        verbose_name="Quy tắc khớp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chi tiết giao dịch",
                "verbose_name_plural": "Chi tiết giao dịch",
                "ordering": ["batch", "transaction_date", "transaction_time"],
                "indexes": [
                    models.Index(
                        fields=["batch", "transaction_date"],
                        name="kpi_tool_te_batch_i_4f839a_idx",
                    ),
                    models.Index(
                        fields=["reference_no"], name="kpi_tool_te_referen_dd0b67_idx"
                    ),
                    models.Index(
                        fields=["is_matched"], name="kpi_tool_te_is_matc_64d1d9_idx"
                    ),
                ],
            },
        ),
    ]
