# Generated by Django 5.2.10 on 2026-01-28 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SavingsProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Tên sản phẩm")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Mã sản phẩm"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Mô tả")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang áp dụng"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Thứ tự hiển thị"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
            ],
            options={
                "verbose_name": "Sản phẩm tiết kiệm",
                "verbose_name_plural": "Sản phẩm tiết kiệm",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="InterestRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "term_month_min",
                    models.PositiveIntegerField(
                        verbose_name="Kỳ hạn tối thiểu (tháng)"
                    ),
                ),
                (
                    "term_month_max",
                    models.PositiveIntegerField(verbose_name="Kỳ hạn tối đa (tháng)"),
                ),
                (
                    "interest_rate_yearly",
                    models.FloatField(verbose_name="Lãi suất %/năm"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text='VD: "6 đến 11 tháng"',
                        max_length=100,
                        verbose_name="Mô tả kỳ hạn",
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        blank=True,
                        help_text="Ngày bắt đầu áp dụng mức lãi suất này",
                        null=True,
                        verbose_name="Ngày hiệu lực",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang áp dụng"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="savings_calculator.savingsproduct",
                        verbose_name="Sản phẩm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lãi suất",
                "verbose_name_plural": "Bảng lãi suất",
                "ordering": ["product", "term_month_min"],
            },
        ),
    ]
