# Generated by Django 5.2.7 on 2026-04-01 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Tên kỳ thi')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Kỳ thi',
                'verbose_name_plural': 'Kỳ thi',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Nội dung câu hỏi')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự')),
                ('explanation', models.TextField(blank=True, verbose_name='Diễn giải')),
                ('search_acronym', models.CharField(blank=True, db_index=True, editable=False, max_length=500, verbose_name='Viết tắt tìm kiếm')),
                ('search_text_normalized', models.TextField(blank=True, db_index=True, editable=False, verbose_name='Nội dung chuẩn hóa')),
            ],
            options={
                'verbose_name': 'Câu hỏi',
                'verbose_name_plural': 'Câu hỏi',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Nội dung lựa chọn')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Là đáp án đúng')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz.question', verbose_name='Câu hỏi')),
            ],
            options={
                'verbose_name': 'Lựa chọn',
                'verbose_name_plural': 'Lựa chọn',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tên đề thi')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='quiz.exam', verbose_name='Kỳ thi')),
            ],
            options={
                'verbose_name': 'Đề thi',
                'verbose_name_plural': 'Đề thi',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quiz', verbose_name='Đề thi'),
        ),
    ]
