# Generated by Django 5.2.7 on 2026-04-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='search_text_normalized',
            field=models.TextField(blank=True, db_index=True, editable=False, verbose_name='Nội dung chuẩn hóa'),
        ),
    ]
