# Generated by Django 5.2.7 on 2026-06-23 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_den', models.DateField(verbose_name='Ngày đến')),
                ('so_den', models.CharField(max_length=100, verbose_name='Số đến')),
                ('tac_gia', models.CharField(max_length=500, verbose_name='Tác giả')),
                ('so_ky_hieu', models.CharField(max_length=200, verbose_name='Số, ký hiệu văn bản')),
                ('ngay_van_ban', models.DateField(verbose_name='Ngày tháng văn bản')),
                ('ten_loai_trich_yeu', models.TextField(verbose_name='Tên loại và trích yếu nội dung văn bản')),
                ('don_vi_nguoi_nhan', models.CharField(max_length=500, verbose_name='Đơn vị hoặc người nhận')),
                ('ngay_chuyen', models.DateField(verbose_name='Ngày chuyển')),
                ('ky_nhan', models.CharField(blank=True, default='', max_length=500, verbose_name='Ký nhận')),
                ('ghi_chu', models.TextField(blank=True, default='', verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_documents_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Văn bản đến',
                'verbose_name_plural': 'Đăng ký văn bản đến',
                'ordering': ['-ngay_den', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OutgoingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_ky_hieu', models.CharField(max_length=200, verbose_name='Số, ký hiệu văn bản')),
                ('ngay_van_ban', models.DateField(verbose_name='Ngày tháng văn bản')),
                ('ten_loai_trich_yeu', models.TextField(verbose_name='Tên loại và trích yếu nội dung văn bản')),
                ('nguoi_ky', models.CharField(choices=[('TCCong', 'Trần Chí Công'), ('NXMo', 'Nguyễn Xuân Mơ'), ('LHNgan', 'La Hoàng Ngân'), ('other', 'Người khác')], max_length=20, verbose_name='Người ký')),
                ('nguoi_ky_khac', models.CharField(blank=True, default='', max_length=200, verbose_name='Tên người ký (khác)')),
                ('noi_nhan_truong_phong', models.BooleanField(default=False, verbose_name='Trưởng các phòng')),
                ('noi_nhan_giam_doc_pgd', models.BooleanField(default=False, verbose_name='Giám đốc phòng Giao dịch')),
                ('noi_nhan_khac', models.TextField(blank=True, default='', verbose_name='Nơi nhận khác')),
                ('don_vi_nhan_ban_luu', models.CharField(blank=True, default='', max_length=500, verbose_name='Đơn vị, người nhận bản lưu')),
                ('so_luong_ban', models.PositiveIntegerField(default=1, verbose_name='Số lượng bản')),
                ('ngay_chuyen', models.DateField(verbose_name='Ngày chuyển')),
                ('ky_nhan', models.CharField(blank=True, default='', max_length=500, verbose_name='Ký nhận')),
                ('ghi_chu', models.TextField(blank=True, default='', verbose_name='Ghi chú')),
                ('loai_chuyen_phat', models.CharField(blank=True, choices=[('', 'Không chọn'), ('noi_bo', 'Văn bản chuyển phát nội bộ'), ('buu_dien', 'Văn bản chuyển phát bưu điện')], default='', max_length=10, verbose_name='Loại chuyển phát')),
                ('so_luong_bi', models.PositiveIntegerField(blank=True, null=True, verbose_name='Số lượng bì')),
                ('ky_nhan_buu_dien', models.CharField(blank=True, default='', max_length=500, verbose_name='Ký nhận và dấu bưu điện')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_documents_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Văn bản đi',
                'verbose_name_plural': 'Đăng ký văn bản đi',
                'ordering': ['-ngay_van_ban', '-id'],
            },
        ),
    ]
