# Generated by Django 5.2.7 on 2025-10-31 18:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Tên danh mục")),
                ("description", models.TextField(blank=True, verbose_name="Mô tả")),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Thứ tự hiển thị"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
            ],
            options={
                "verbose_name": "Danh mục",
                "verbose_name_plural": "Danh mục",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Variable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Tên biến (không dấu, không khoảng trắng)",
                    ),
                ),
                (
                    "label",
                    models.CharField(max_length=200, verbose_name="Nhãn hiển thị"),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Văn bản"),
                            ("textarea", "Đoạn văn"),
                            ("date", "Ngày tháng"),
                            ("number", "Con số"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="Kiểu dữ liệu",
                    ),
                ),
                (
                    "help_text",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Gợi ý nhập liệu"
                    ),
                ),
                (
                    "required",
                    models.BooleanField(default=True, verbose_name="Bắt buộc nhập"),
                ),
                (
                    "default_value",
                    models.TextField(blank=True, verbose_name="Giá trị mặc định"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
            ],
            options={
                "verbose_name": "Biến",
                "verbose_name_plural": "Biến",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Tên mẫu biểu")),
                ("description", models.TextField(blank=True, verbose_name="Mô tả")),
                (
                    "file",
                    models.FileField(
                        upload_to="templates/docx/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["docx"]
                            )
                        ],
                        verbose_name="File Word (.docx)",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Thứ tự hiển thị"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Kích hoạt"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "allowed_groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="templates",
                        to="auth.group",
                        verbose_name="Nhóm được phép truy cập",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="templates_app.category",
                        verbose_name="Danh mục",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mẫu biểu",
                "verbose_name_plural": "Mẫu biểu",
                "ordering": ["category", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="TemplateVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, verbose_name="Thứ tự hiển thị trong form"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="templates_app.template",
                        verbose_name="Mẫu biểu",
                    ),
                ),
                (
                    "variable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="templates_app.variable",
                        verbose_name="Biến",
                    ),
                ),
            ],
            options={
                "verbose_name": "Biến của mẫu biểu",
                "verbose_name_plural": "Biến của mẫu biểu",
                "ordering": ["order", "variable__name"],
                "unique_together": {("template", "variable")},
            },
        ),
        migrations.AddField(
            model_name="template",
            name="variables",
            field=models.ManyToManyField(
                related_name="templates",
                through="templates_app.TemplateVariable",
                to="templates_app.variable",
                verbose_name="Biến",
            ),
        ),
    ]
