# Generated by Django 5.2.7 on 2025-11-01 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ho_ten",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="Họ và tên"
                    ),
                ),
                (
                    "ngay_sinh",
                    models.DateField(blank=True, null=True, verbose_name="Ngày sinh"),
                ),
                (
                    "gioi_tinh",
                    models.CharField(
                        choices=[("Nam", "Nam"), ("Nữ", "Nữ"), ("Khác", "Khác")],
                        default="Nam",
                        max_length=10,
                        verbose_name="Giới tính",
                    ),
                ),
                (
                    "so_cmnd",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        unique=True,
                        verbose_name="Số CMND/CCCD",
                    ),
                ),
                (
                    "ngay_cap_cmnd",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ngày cấp CMND/CCCD"
                    ),
                ),
                (
                    "noi_cap_cmnd",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nơi cấp CMND/CCCD"
                    ),
                ),
                (
                    "dia_chi",
                    models.TextField(blank=True, verbose_name="Địa chỉ thường trú"),
                ),
                (
                    "dia_chi_tam_tru",
                    models.TextField(blank=True, verbose_name="Địa chỉ tạm trú"),
                ),
                (
                    "so_dien_thoai",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=20,
                        verbose_name="Số điện thoại",
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "nghe_nghiep",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nghề nghiệp"
                    ),
                ),
                (
                    "noi_lam_viec",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nơi làm việc"
                    ),
                ),
                (
                    "chuc_vu",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Chức vụ"
                    ),
                ),
                (
                    "thu_nhap_hang_thang",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=15,
                        null=True,
                        verbose_name="Thu nhập hàng tháng (VNĐ)",
                    ),
                ),
                (
                    "so_tai_khoan",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Số tài khoản"
                    ),
                ),
                (
                    "loai_tai_khoan",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Loại tài khoản"
                    ),
                ),
                ("ghi_chu", models.TextField(blank=True, verbose_name="Ghi chú")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người tạo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Khách hàng",
                "verbose_name_plural": "Khách hàng",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["ho_ten", "so_cmnd"],
                        name="templates_a_ho_ten_276fb8_idx",
                    ),
                    models.Index(
                        fields=["so_dien_thoai"], name="templates_a_so_dien_aba29a_idx"
                    ),
                ],
            },
        ),
    ]
