# Generated by Django 5.2.7 on 2025-11-01 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates_app", "0002_customer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="chuc_vu",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="dia_chi_tam_tru",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="thu_nhap_hang_thang",
        ),
        migrations.AddField(
            model_name="customer",
            name="ma_khach_hang",
            field=models.CharField(
                blank=True, db_index=True, max_length=50, verbose_name="Mã khách hàng"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="nghe_nghiep",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Công chức viên chức", "Công chức viên chức"),
                    ("Kinh doanh tự do", "Kinh doanh tự do"),
                    ("Nội trợ", "Nội trợ"),
                    ("Khác", "Khác"),
                ],
                max_length=200,
                verbose_name="Nghề nghiệp",
            ),
        ),
    ]
