# Generated by Django 5.2.7 on 2025-11-01 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates_app", "0003_remove_customer_chuc_vu_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="noi_cap_cmnd_custom",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Nơi cấp CMND/CCCD (tùy chỉnh)"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="noi_cap_cmnd",
            field=models.CharField(
                choices=[
                    ("Cục CSQLHC về TTXH", "Cục CSQLHC về TTXH"),
                    ("Bộ Công An", "Bộ Công An"),
                    ("Khác", "Khác"),
                ],
                default="Cục CSQLHC về TTXH",
                max_length=50,
                verbose_name="Nơi cấp CMND/CCCD",
            ),
        ),
        migrations.CreateModel(
            name="BranchConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten_chi_nhanh",
                    models.CharField(
                        default="Chi nhánh Giá Rai Bạc Liêu",
                        max_length=200,
                        verbose_name="Tên chi nhánh",
                    ),
                ),
                (
                    "ten_chi_nhanh_hoa",
                    models.CharField(
                        default="CHI NHÁNH GIÁ RAI BẠC LIÊU",
                        max_length=200,
                        verbose_name="Tên chi nhánh (IN HOA)",
                    ),
                ),
                (
                    "mst",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Mã số thuế"
                    ),
                ),
                (
                    "giao_dich_vien",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Giao dịch viên"
                    ),
                ),
                (
                    "kiem_soat_vien",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Kiểm soát viên"
                    ),
                ),
                (
                    "giam_doc",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Giám đốc"
                    ),
                ),
                (
                    "dia_chi_chi_nhanh",
                    models.TextField(blank=True, verbose_name="Địa chỉ chi nhánh"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người cập nhật",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cấu hình Chi nhánh",
                "verbose_name_plural": "Cấu hình Chi nhánh",
            },
        ),
    ]
