# Generated by Django 5.2.7 on 2025-11-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates_app", "0005_globalconfig_delete_branchconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="cif",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Mã CIF",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="dv_bankplus",
            field=models.BooleanField(default=False, verbose_name="Dịch vụ: Bankplus"),
        ),
        migrations.AddField(
            model_name="customer",
            name="dv_e_commerce",
            field=models.BooleanField(
                default=False, verbose_name="Dịch vụ: E-Commerce"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="dv_e_mobile",
            field=models.BooleanField(default=False, verbose_name="Dịch vụ: E-Mobile"),
        ),
        migrations.AddField(
            model_name="customer",
            name="dv_retail_ebanking",
            field=models.BooleanField(
                default=False, verbose_name="Dịch vụ: Retail E-banking"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="dv_smart_otp",
            field=models.BooleanField(default=False, verbose_name="Dịch vụ: Smart OTP"),
        ),
        migrations.AddField(
            model_name="customer",
            name="dv_sms_banking",
            field=models.BooleanField(
                default=False, verbose_name="Dịch vụ: SMS Banking"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="dv_soft_otp",
            field=models.BooleanField(default=False, verbose_name="Dịch vụ: Soft OTP"),
        ),
        migrations.AddField(
            model_name="customer",
            name="dv_thu_ho_bao_hiem",
            field=models.BooleanField(default=False, verbose_name="Thủ hộ: Bảo hiểm"),
        ),
        migrations.AddField(
            model_name="customer",
            name="dv_thu_ho_hoc_phi",
            field=models.BooleanField(default=False, verbose_name="Thủ hộ: Học phí"),
        ),
        migrations.AddField(
            model_name="customer",
            name="dv_thu_ho_tien_dien",
            field=models.BooleanField(default=False, verbose_name="Thủ hộ: Tiền điện"),
        ),
        migrations.AddField(
            model_name="customer",
            name="dv_thu_ho_tien_nuoc",
            field=models.BooleanField(default=False, verbose_name="Thủ hộ: Tiền nước"),
        ),
        migrations.AddField(
            model_name="customer",
            name="dv_thu_ho_vien_thong",
            field=models.BooleanField(default=False, verbose_name="Thủ hộ: Viễn thông"),
        ),
        migrations.AddField(
            model_name="customer",
            name="hang_the",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Classic", "Classic"),
                    ("Gold", "Gold"),
                    ("Platinum", "Platinum"),
                ],
                max_length=20,
                verbose_name="Hạng thẻ",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="kenh_internet",
            field=models.BooleanField(
                default=False, verbose_name="Kênh: Internet Banking"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="kenh_mobile",
            field=models.BooleanField(default=False, verbose_name="Kênh: Mobile"),
        ),
        migrations.AddField(
            model_name="customer",
            name="loai_the",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Thẻ ATM", "Thẻ ATM"),
                    ("Thẻ Visa", "Thẻ Visa"),
                    ("Thẻ MasterCard", "Thẻ MasterCard"),
                    ("Thẻ JCB", "Thẻ JCB"),
                ],
                max_length=50,
                verbose_name="Loại thẻ",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="loai_tien_te",
            field=models.CharField(
                choices=[("VND", "VND - Việt Nam Đồng"), ("USD", "USD - Đô la Mỹ")],
                default="VND",
                max_length=10,
                verbose_name="Loại tiền tệ",
            ),
        ),
    ]
