# Generated by Django 4.2.25 on 2025-11-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0006_customer_cif_customer_dv_bankplus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='loai_the',
            field=models.CharField(blank=True, choices=[('The Plus Success', 'The Plus Success'), ('Agribank Debit Card', 'Agribank Debit Card'), ('Thẻ Visa', 'Thẻ Visa'), ('Thẻ MasterCard', 'Thẻ MasterCard'), ('Thẻ JCB', 'Thẻ JCB')], max_length=50, verbose_name='Loại thẻ'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nghe_nghiep',
            field=models.CharField(blank=True, choices=[('Công chức viên chức', 'Công chức viên chức'), ('Nông dân', 'Nông dân'), ('Giáo viên/Bác Sĩ', 'Giáo viên/Bác Sĩ'), ('Công nhân', 'Công nhân'), ('Kinh doanh tự do', 'Kinh doanh tự do'), ('Học sinh/Sinh viên', 'Học sinh/Sinh viên'), ('Nội trợ', 'Nội trợ'), ('Khác', 'Khác')], max_length=200, verbose_name='Nghề nghiệp'),
        ),
    ]
