# Generated by Django 5.2.7 on 2025-11-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates_app", "0007_alter_customer_loai_the_alter_customer_nghe_nghiep"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="ngay_in",
            field=models.DateField(
                blank=True, null=True, verbose_name="Ngày in mẫu biểu"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="phat_hanh_lai",
            field=models.BooleanField(default=False, verbose_name="Phát hành lại"),
        ),
        migrations.AddField(
            model_name="customer",
            name="phat_hanh_lan_dau",
            field=models.BooleanField(default=False, verbose_name="Phát hành lần đầu"),
        ),
        migrations.AddField(
            model_name="customer",
            name="so_tai_khoan_yc",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="Số tài khoản theo yêu cầu"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="hang_the",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Hạng chuẩn", "Hạng chuẩn"),
                    ("Hạng vàng", "Hạng vàng"),
                    ("Classic", "Classic"),
                    ("Gold", "Gold"),
                    ("Platinum", "Platinum"),
                ],
                max_length=20,
                verbose_name="Hạng thẻ",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="loai_tai_khoan",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Tài khoản ngẫu nhiên", "Tài khoản ngẫu nhiên"),
                    ("Tài khoản số theo yêu cầu", "Tài khoản số theo yêu cầu"),
                ],
                max_length=100,
                verbose_name="Loại tài khoản",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="loai_the",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Thẻ Ghi nợ nội địa", "Thẻ Ghi nợ nội địa"),
                    ("The Plus Success", "The Plus Success"),
                    ("Agribank Debit Card", "Agribank Debit Card"),
                    ("Thẻ Visa", "Thẻ Visa"),
                    ("Thẻ MasterCard", "Thẻ MasterCard"),
                    ("Thẻ JCB", "Thẻ JCB"),
                ],
                max_length=50,
                verbose_name="Loại thẻ",
            ),
        ),
    ]
