# Generated by Django 5.2.7 on 2025-11-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates_app", "0008_customer_ngay_in_customer_phat_hanh_lai_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="visible_field_groups",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Danh sách các nhóm trường cần hiển thị trong form. VD: ['personal_info', 'banking', 'services']",
                verbose_name="Nhóm trường hiển thị",
            ),
        ),
    ]
