# Generated by Django 5.2.7 on 2025-11-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates_app", "0009_category_visible_field_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="ngay_het_han_cmnd",
            field=models.DateField(
                blank=True, null=True, verbose_name="Ngày hết hạn CMND/CCCD"
            ),
        ),
    ]
