# Generated by Django 5.2.7 on 2025-11-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0010_add_id_card_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ma_noi_cap_cmnd',
            field=models.CharField(blank=True, max_length=10, verbose_name='Mã nơi cấp CMND/CCCD'),
        ),
        migrations.AddField(
            model_name='customer',
            name='ma_phuong_xa',
            field=models.CharField(blank=True, max_length=10, verbose_name='Mã phường/xã'),
        ),
        migrations.AddField(
            model_name='customer',
            name='ma_quan_huyen',
            field=models.CharField(blank=True, max_length=10, verbose_name='Mã quận/huyện'),
        ),
        migrations.AddField(
            model_name='customer',
            name='ma_so_thue',
            field=models.CharField(blank=True, max_length=20, verbose_name='Mã số thuế'),
        ),
        migrations.AddField(
            model_name='customer',
            name='ma_tinh',
            field=models.CharField(blank=True, max_length=10, verbose_name='Mã tỉnh/thành phố'),
        ),
        migrations.AddField(
            model_name='customer',
            name='quoc_tich',
            field=models.CharField(blank=True, default='VN', max_length=10, verbose_name='Quốc tịch'),
        ),
        migrations.AddField(
            model_name='customer',
            name='so_ho_chieu',
            field=models.CharField(blank=True, max_length=20, verbose_name='Số hộ chiếu'),
        ),
    ]
