# Generated by Django 5.2.7 on 2025-11-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0011_customer_ma_noi_cap_cmnd_customer_ma_phuong_xa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='dan_toc',
            field=models.CharField(blank=True, default='Kinh', max_length=50, verbose_name='Dân tộc'),
        ),
        migrations.AddField(
            model_name='customer',
            name='ho_khau',
            field=models.TextField(blank=True, verbose_name='Hộ khẩu thường trú'),
        ),
        migrations.AddField(
            model_name='customer',
            name='ho_ten_tieng_anh',
            field=models.CharField(blank=True, max_length=200, verbose_name='Họ và tên tiếng Anh'),
        ),
        migrations.AddField(
            model_name='customer',
            name='loai_phi',
            field=models.CharField(blank=True, max_length=100, verbose_name='Loại phí'),
        ),
        migrations.AddField(
            model_name='customer',
            name='ngay_tra_the',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày trả thẻ'),
        ),
        migrations.AddField(
            model_name='customer',
            name='so_the_atm',
            field=models.CharField(blank=True, max_length=20, verbose_name='Số thẻ ATM'),
        ),
        migrations.AddField(
            model_name='customer',
            name='thoi_han_the',
            field=models.CharField(blank=True, max_length=50, verbose_name='Thời hạn thẻ'),
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='dia_danh',
            field=models.CharField(blank=True, help_text='Ví dụ: Bạc Liêu, Đồng Tháp', max_length=200, verbose_name='Địa danh'),
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='dien_thoai_chi_nhanh',
            field=models.CharField(blank=True, max_length=50, verbose_name='Điện thoại chi nhánh'),
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='ma_chi_nhanh',
            field=models.CharField(blank=True, max_length=20, verbose_name='Mã chi nhánh'),
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='so_fax',
            field=models.CharField(blank=True, max_length=50, verbose_name='Số Fax'),
        ),
    ]
