# Generated by Django 5.2.7 on 2025-11-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates_app", "0013_add_new_occupation_and_card_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="ket_qua_phan_loai_kh",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "--- Chọn ---"),
                    ("Cao", "Cao"),
                    ("Trung bình", "Trung bình"),
                    ("Thấp", "Thấp"),
                ],
                max_length=20,
                verbose_name="Kết quả phân loại KH",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="loai_tai_khoan",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Tài khoản ngẫu nhiên", "Tài khoản ngẫu nhiên"),
                    ("Tài khoản số theo yêu cầu", "Tài khoản số theo yêu cầu"),
                    ("Tài khoản chuyên dụng", "Tài khoản chuyên dụng"),
                ],
                max_length=100,
                verbose_name="Loại tài khoản",
            ),
        ),
    ]
