# Generated by Django 5.2.7 on 2025-11-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0017_add_customer_classification_to_field_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='nghe_nghiep',
            field=models.CharField(blank=True, choices=[('Công chức viên chức', 'Công chức viên chức'), ('Nông dân', 'Nông dân'), ('Giáo viên/Bác Sĩ', 'Giáo viên/Bác Sĩ'), ('Giáo viên', 'Giáo viên'), ('Bác sĩ', 'Bác sĩ'), ('Công nhân', 'Công nhân'), ('Kinh doanh tự do', 'Kinh doanh tự do'), ('Học sinh/Sinh viên', 'Học sinh/Sinh viên'), ('Nội trợ', 'Nội trợ'), ('Công an/Bộ đội', 'Công an/Bộ đội'), ('Kỹ sư', 'Kỹ sư'), ('Khác', 'Khác')], max_length=200, verbose_name='Nghề nghiệp'),
        ),
    ]
