# Generated by Django 5.2.7 on 2025-11-15 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0020_add_beautiful_number_model'),
        ('templates_app', '0020_merge_20251115_1533'),
    ]

    operations = [
    ]
