# Generated by Django 5.2.7 on 2025-11-15 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0021_merge_20251115_1653'),
        ('templates_app', '0021_seed_beautiful_numbers'),
    ]

    operations = [
    ]
