# Generated by Django 5.2.7 on 2025-11-15 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0022_merge_20251115_1705'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='beautifulnumber',
            new_name='templates_a_categor_d6f839_idx',
            old_name='templates_a_categor_idx',
        ),
    ]
