# Generated by Django 5.2.7 on 2025-11-15 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0018_alter_customer_nghe_nghiep'),
        ('templates_app', '0022_seed_beautiful_numbers'),
    ]

    operations = [
    ]
