# Generated by Django 5.2.7 on 2025-11-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "templates_app",
            "0024_rename_templates_a_categor_idx_templates_a_categor_d6f839_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="district",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Quận/Huyện"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="full_address",
            field=models.TextField(blank=True, verbose_name="Địa chỉ đầy đủ"),
        ),
        migrations.AddField(
            model_name="customer",
            name="hamlet",
            field=models.CharField(blank=True, max_length=200, verbose_name="Ấp/Khóm"),
        ),
        migrations.AddField(
            model_name="customer",
            name="province",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Tỉnh/Thành phố"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="ward",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Phường/Xã"
            ),
        ),
        migrations.AlterField(
            model_name="beautifulnumber",
            name="price_tier",
            field=models.CharField(
                choices=[
                    ("500K-1M", "550,000 - 1,100,000 VNĐ"),
                    ("1M-3M", "1,100,000 - 3,300,000 VNĐ"),
                    ("3M-5M", "3,300,000 - 5,500,000 VNĐ"),
                    ("5M-10M", "5,500,000 - 11,000,000 VNĐ"),
                    ("10M-20M", "11,000,000 - 22,000,000 VNĐ"),
                    ("20M+", "Trên 22,000,000 VNĐ"),
                ],
                db_index=True,
                max_length=20,
                verbose_name="Mức giá",
            ),
        ),
    ]
