# Generated by Django 5.2.7 on 2025-11-17 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0026_bankstatement_transaction'),
    ]

    operations = [
        #migrations.RenameIndex(
        #    model_name='transaction',
        #    new_name='templates_a_stateme_ebfbe4_idx',
        #    old_name='templates_a_stateme_cc7929_idx',
        #),
        #migrations.RenameIndex(
        #    model_name='transaction',
        #    new_name='templates_a_transac_13f2f1_idx',
        #    old_name='templates_a_transac_d8c5c0_idx',
        #),
    ]
