# Generated by Django 5.2.7 on 2025-11-18 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0027_rename_templates_a_stateme_cc7929_idx_templates_a_stateme_ebfbe4_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên khóa học')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc')),
                ('description', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Khóa học',
                'verbose_name_plural': 'Khóa học',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(help_text='Mã nhân viên (khác với username)', max_length=50, unique=True, verbose_name='Mã nhân viên')),
                ('full_name', models.CharField(max_length=200, verbose_name='Họ và tên')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('gender', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ'), ('Khác', 'Khác')], default='Nam', max_length=10, verbose_name='Giới tính')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('address', models.TextField(blank=True, verbose_name='Địa chỉ')),
                ('id_card_number', models.CharField(blank=True, max_length=20, verbose_name='Số CCCD')),
                ('id_card_date', models.DateField(blank=True, null=True, verbose_name='Ngày cấp CCCD')),
                ('id_card_place', models.CharField(blank=True, max_length=200, verbose_name='Nơi cấp CCCD')),
                ('branch', models.CharField(blank=True, choices=[('HOI_SO', 'Hội sở Giá Rai Bạc Liêu'), ('PGD_P1', 'Phòng Giao dịch Phường 1'), ('PGD_LANG_TRON', 'Phòng Giao dịch Láng Tròn')], max_length=50, verbose_name='Chi nhánh')),
                ('department', models.CharField(blank=True, choices=[('KE_TOAN', 'Phòng Kế toán & Ngân quỹ'), ('KHACH_HANG', 'Phòng Khách hàng'), ('BAN_GIAM_DOC', 'Ban Giám đốc'), ('TONG_HOP', 'Phòng Tổng hợp')], max_length=50, verbose_name='Phòng ban')),
                ('job_function', models.CharField(blank=True, choices=[('GIAO_DICH_VIEN', 'Giao dịch viên'), ('KIEM_SOAT_VIEN', 'Kiểm soát viên'), ('HAU_KIEM_VIEN', 'Hậu kiểm viên'), ('TONG_HOP_VIEN', 'Tổng hợp viên')], max_length=50, verbose_name='Nghiệp vụ')),
                ('position', models.CharField(blank=True, choices=[('GIAM_DOC', 'Giám đốc'), ('PHO_GIAM_DOC', 'Phó Giám Đốc'), ('TRUONG_PHONG', 'Trưởng phòng'), ('PHO_PHONG', 'Phó phòng'), ('GD_PGD', 'Giám đốc Phòng Giao dịch'), ('PGD_PGD', 'Phó Giám đốc Phòng giao dịch'), ('NHAN_VIEN', 'Nhân viên')], max_length=50, verbose_name='Chức vụ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Hồ sơ nhân viên',
                'verbose_name_plural': 'Hồ sơ nhân viên',
                'ordering': ['employee_code'],
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Đã hoàn thành')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='Ngày hoàn thành')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày ghi danh')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='templates_app.course', verbose_name='Khóa học')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Người học')),
            ],
            options={
                'verbose_name': 'Ghi danh khóa học',
                'verbose_name_plural': 'Ghi danh khóa học',
                'ordering': ['course', 'user__username'],
                'unique_together': {('course', 'user')},
            },
        ),
    ]
