# Generated by Django 5.2.7 on 2025-11-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0028_course_userprofile_courseenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='certificate_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Mã chứng thư số'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='certificate_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Chứng thư số đến ngày'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='certificate_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Chứng thư số từ ngày'),
        ),
    ]
