# Generated by Django 5.2.7 on 2025-11-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0030_add_joint_savings_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='visible_field_groups',
            field=models.JSONField(blank=True, default=list, help_text="Danh sách các nhóm trường cần hiển thị trong form. VD: ['customer_basic_info', 'banking', 'card']", verbose_name='Nhóm trường hiển thị'),
        ),
    ]
