# Generated by Django 5.2.7 on 2025-11-27 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates_app", "0032_add_foreign_currency_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ATM",
            fields=[
                (
                    "machine_id",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Máy ATM",
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Số Serial máy"
                    ),
                ),
                (
                    "address",
                    models.CharField(max_length=500, verbose_name="Địa chỉ máy"),
                ),
                (
                    "machine_type",
                    models.CharField(max_length=100, verbose_name="Loại máy"),
                ),
                (
                    "machine_line",
                    models.CharField(max_length=100, verbose_name="Dòng máy"),
                ),
                (
                    "installation_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ngày lắp đặt"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang hoạt động"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
            ],
            options={
                "verbose_name": "Máy ATM",
                "verbose_name_plural": "Máy ATM",
                "ordering": ["machine_id"],
            },
        ),
        migrations.CreateModel(
            name="ATMDiscrepancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200, verbose_name="Họ tên")),
                (
                    "account_number",
                    models.CharField(max_length=50, verbose_name="Số tài khoản"),
                ),
                ("card_number", models.CharField(max_length=50, verbose_name="Số thẻ")),
                (
                    "trace_number",
                    models.CharField(max_length=100, verbose_name="Số trace"),
                ),
                (
                    "transaction_id",
                    models.CharField(max_length=100, verbose_name="ID giao dịch"),
                ),
                (
                    "discrepancy_type",
                    models.CharField(
                        choices=[("surplus", "Thừa"), ("deficit", "Thiếu")],
                        max_length=10,
                        verbose_name="Loại",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=15, verbose_name="Số tiền"
                    ),
                ),
                (
                    "audit_cycle_start",
                    models.DateField(verbose_name="Chu kỳ kiểm quỹ từ ngày"),
                ),
                (
                    "audit_cycle_end",
                    models.DateField(verbose_name="Chu kỳ kiểm quỹ đến ngày"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Chờ xử lý"),
                            ("resolved", "Đã xử lý"),
                            ("escalated", "Đã báo cáo lên"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Ghi chú")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
            ],
            options={
                "verbose_name": "Giao dịch thừa/thiếu quỹ ATM",
                "verbose_name_plural": "Giao dịch thừa/thiếu quỹ ATM",
                "ordering": ["-audit_cycle_end", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ATMManagementBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("team_leader", "Trưởng Ban"),
                            ("treasury_head", "Trưởng phòng KTNQ"),
                            ("atm_officer", "Cán bộ phụ trách ATM"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Chức vụ",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="Họ và tên"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Chức danh"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang hoạt động"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
            ],
            options={
                "verbose_name": "Ban quản lý ATM",
                "verbose_name_plural": "Ban quản lý ATM",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="ATMReplenishment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("replenishment_date", models.DateField(verbose_name="Ngày tiếp quỹ")),
                (
                    "bills_50k",
                    models.IntegerField(default=0, verbose_name="Số tờ 50.000đ"),
                ),
                (
                    "bills_100k",
                    models.IntegerField(default=0, verbose_name="Số tờ 100.000đ"),
                ),
                (
                    "bills_200k",
                    models.IntegerField(default=0, verbose_name="Số tờ 200.000đ"),
                ),
                (
                    "bills_500k",
                    models.IntegerField(default=0, verbose_name="Số tờ 500.000đ"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
            ],
            options={
                "verbose_name": "Phiếu tiếp quỹ ATM",
                "verbose_name_plural": "Phiếu tiếp quỹ ATM",
                "ordering": ["-replenishment_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Tên khóa học")),
                ("start_date", models.DateField(verbose_name="Ngày bắt đầu")),
                ("end_date", models.DateField(verbose_name="Ngày kết thúc")),
                ("description", models.TextField(blank=True, verbose_name="Ghi chú")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
            ],
            options={
                "verbose_name": "Khóa học",
                "verbose_name_plural": "Khóa học",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="CourseEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Đã hoàn thành"),
                ),
                (
                    "completion_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ngày hoàn thành"
                    ),
                ),
                (
                    "enrolled_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Ngày ghi danh"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ghi danh khóa học",
                "verbose_name_plural": "Ghi danh khóa học",
                "ordering": ["course", "user__username"],
            },
        ),
        migrations.CreateModel(
            name="MailEnvelopeTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "envelope_code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Mã bì thư"
                    ),
                ),
                ("receive_date", models.DateField(verbose_name="Ngày nhận")),
                (
                    "receiver",
                    models.CharField(max_length=200, verbose_name="Người nhận"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Ngày tạo record"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
            ],
            options={
                "verbose_name": "Bì thư",
                "verbose_name_plural": "Quản lý Bì thư",
                "ordering": ["-receive_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "person_type",
                    models.CharField(
                        choices=[("driver", "Tài xế"), ("guard", "Bảo vệ")],
                        max_length=20,
                        verbose_name="Loại nhân viên",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="Họ và tên"),
                ),
                ("id_number", models.CharField(max_length=50, verbose_name="Số CCCD")),
                ("id_issue_date", models.DateField(verbose_name="Ngày cấp")),
                (
                    "id_issue_place",
                    models.CharField(max_length=200, verbose_name="Nơi cấp"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang hoạt động"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
            ],
            options={
                "verbose_name": "Nhân viên vận chuyển",
                "verbose_name_plural": "Nhân viên vận chuyển",
                "ordering": ["person_type", "full_name"],
            },
        ),
        migrations.CreateModel(
            name="ReportConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("lai_ton_dong", "Báo cáo Lãi tồn đọng"),
                            ("phat_hanh_the", "Báo cáo Phát hành thẻ"),
                            ("luong", "Chuyển đổi file Lương"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Loại báo cáo",
                    ),
                ),
                (
                    "config_data",
                    models.JSONField(default=dict, verbose_name="Dữ liệu cấu hình"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Kích hoạt"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
            ],
            options={
                "verbose_name": "Cấu hình báo cáo",
                "verbose_name_plural": "Cấu hình báo cáo",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_code",
                    models.CharField(
                        help_text="Mã nhân viên (khác với username)",
                        max_length=50,
                        unique=True,
                        verbose_name="Mã nhân viên",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="Họ và tên"),
                ),
                (
                    "dob",
                    models.DateField(blank=True, null=True, verbose_name="Ngày sinh"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("Nam", "Nam"), ("Nữ", "Nữ"), ("Khác", "Khác")],
                        default="Nam",
                        max_length=10,
                        verbose_name="Giới tính",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Số điện thoại"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Địa chỉ")),
                (
                    "id_card_number",
                    models.CharField(blank=True, max_length=20, verbose_name="Số CCCD"),
                ),
                (
                    "id_card_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ngày cấp CCCD"
                    ),
                ),
                (
                    "id_card_place",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nơi cấp CCCD"
                    ),
                ),
                (
                    "branch",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("HOI_SO", "Hội sở Giá Rai Bạc Liêu"),
                            ("PGD_P1", "Phòng Giao dịch Phường 1"),
                            ("PGD_LANG_TRON", "Phòng Giao dịch Láng Tròn"),
                        ],
                        max_length=50,
                        verbose_name="Chi nhánh",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("KE_TOAN", "Phòng Kế toán & Ngân quỹ"),
                            ("KHACH_HANG", "Phòng Khách hàng"),
                            ("BAN_GIAM_DOC", "Ban Giám đốc"),
                            ("TONG_HOP", "Phòng Tổng hợp"),
                        ],
                        max_length=50,
                        verbose_name="Phòng ban",
                    ),
                ),
                (
                    "job_function",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GIAO_DICH_VIEN", "Giao dịch viên"),
                            ("KIEM_SOAT_VIEN", "Kiểm soát viên"),
                            ("HAU_KIEM_VIEN", "Hậu kiểm viên"),
                            ("TONG_HOP_VIEN", "Tổng hợp viên"),
                        ],
                        max_length=50,
                        verbose_name="Nghiệp vụ",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GIAM_DOC", "Giám đốc"),
                            ("PHO_GIAM_DOC", "Phó Giám Đốc"),
                            ("TRUONG_PHONG", "Trưởng phòng"),
                            ("PHO_PHONG", "Phó phòng"),
                            ("GD_PGD", "Giám đốc Phòng Giao dịch"),
                            ("PGD_PGD", "Phó Giám đốc Phòng giao dịch"),
                            ("NHAN_VIEN", "Nhân viên"),
                        ],
                        max_length=50,
                        verbose_name="Chức vụ",
                    ),
                ),
                (
                    "certificate_code",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Mã chứng thư số"
                    ),
                ),
                (
                    "certificate_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Chứng thư số từ ngày"
                    ),
                ),
                (
                    "certificate_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Chứng thư số đến ngày"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
            ],
            options={
                "verbose_name": "Hồ sơ nhân viên",
                "verbose_name_plural": "Hồ sơ nhân viên",
                "ordering": ["employee_code"],
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "license_plate",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Biển số xe"
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Loại xe"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang hoạt động"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
            ],
            options={
                "verbose_name": "Phương tiện",
                "verbose_name_plural": "Phương tiện",
                "ordering": ["license_plate"],
            },
        ),
        migrations.RenameIndex(
            model_name="transaction",
            new_name="templates_a_stateme_ebfbe4_idx",
            old_name="templates_a_stateme_cc7929_idx",
        ),
        migrations.RenameIndex(
            model_name="transaction",
            new_name="templates_a_transac_13f2f1_idx",
            old_name="templates_a_transac_d8c5c0_idx",
        ),
        migrations.AlterField(
            model_name="category",
            name="visible_field_groups",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Danh sách các nhóm trường cần hiển thị trong form. VD: ['customer_basic_info', 'banking', 'card']",
                verbose_name="Nhóm trường hiển thị",
            ),
        ),
        migrations.AddField(
            model_name="atmdiscrepancy",
            name="atm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="discrepancies",
                to="templates_app.atm",
                verbose_name="Máy ATM",
            ),
        ),
        migrations.AddField(
            model_name="atmdiscrepancy",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="atm_discrepancies_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người tạo",
            ),
        ),
        migrations.AddField(
            model_name="atmreplenishment",
            name="atm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="templates_app.atm",
                verbose_name="Máy ATM",
            ),
        ),
        migrations.AddField(
            model_name="atmreplenishment",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người tạo",
            ),
        ),
        migrations.AddField(
            model_name="courseenrollment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="templates_app.course",
                verbose_name="Khóa học",
            ),
        ),
        migrations.AddField(
            model_name="courseenrollment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_enrollments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người học",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="person",
            unique_together={("id_number", "person_type")},
        ),
        migrations.AddField(
            model_name="atmreplenishment",
            name="driver",
            field=models.ForeignKey(
                limit_choices_to={"person_type": "driver"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="replenishments_as_driver",
                to="templates_app.person",
                verbose_name="Tài xế",
            ),
        ),
        migrations.AddField(
            model_name="atmreplenishment",
            name="guard",
            field=models.ForeignKey(
                limit_choices_to={"person_type": "guard"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="replenishments_as_guard",
                to="templates_app.person",
                verbose_name="Bảo vệ",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Tài khoản",
            ),
        ),
        migrations.AddField(
            model_name="atmreplenishment",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="templates_app.vehicle",
                verbose_name="Phương tiện",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="courseenrollment",
            unique_together={("course", "user")},
        ),
    ]
