# Generated by Django 5.2.7 on 2025-12-11 01:41

import django.core.validators
import templates_app.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates_app", "0033_atm_atmdiscrepancy_atmmanagementboard_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="file",
            field=models.FileField(
                storage=templates_app.storage.HybridTemplateStorage(),
                upload_to="templates/docx/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["docx"]
                    )
                ],
                verbose_name="File Word (.docx)",
            ),
        ),
    ]
