# Generated by Django 5.2.7 on 2025-12-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates_app", "0034_alter_template_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cif",
                    models.CharField(
                        db_index=True, max_length=20, unique=True, verbose_name="Mã CIF"
                    ),
                ),
                (
                    "so_tai_khoan",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Số tài khoản"
                    ),
                ),
                (
                    "ten_doanh_nghiep",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Tên doanh nghiệp"
                    ),
                ),
                (
                    "loai_giay_to",
                    models.CharField(
                        choices=[
                            ("GCN", "Giấy chứng nhận đăng ký doanh nghiệp"),
                            ("DKKD", "Giấy đăng ký kinh doanh"),
                            ("QD", "Quyết định thành lập"),
                        ],
                        default="GCN",
                        max_length=10,
                        verbose_name="Loại giấy tờ định danh",
                    ),
                ),
                (
                    "so_gcn",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        verbose_name="Số GCN đăng ký DN/Giấy ĐKKD/QĐ thành lập",
                    ),
                ),
                (
                    "ngay_cap_gcn",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ngày cấp GCN"
                    ),
                ),
                (
                    "noi_cap_gcn",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nơi cấp GCN"
                    ),
                ),
                (
                    "ma_so_thue",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Mã số thuế"
                    ),
                ),
                (
                    "ngay_cap_mst",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ngày cấp MST"
                    ),
                ),
                (
                    "noi_cap_mst",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nơi cấp MST"
                    ),
                ),
                ("dia_chi", models.TextField(blank=True, verbose_name="Địa chỉ")),
                (
                    "dien_thoai",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Điện thoại"
                    ),
                ),
                (
                    "linh_vuc_kinh_doanh",
                    models.TextField(
                        blank=True, verbose_name="Lĩnh vực hoạt động kinh doanh"
                    ),
                ),
                (
                    "von_dieu_le",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=20,
                        null=True,
                        verbose_name="Vốn điều lệ (VND)",
                    ),
                ),
                (
                    "nguoi_dai_dien_ho_ten",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Người đại diện - Họ và tên",
                    ),
                ),
                (
                    "nguoi_dai_dien_ngay_sinh",
                    models.DateField(
                        blank=True, null=True, verbose_name="Người đại diện - Ngày sinh"
                    ),
                ),
                (
                    "nguoi_dai_dien_gioi_tinh",
                    models.CharField(
                        blank=True,
                        choices=[("Nam", "Nam"), ("Nữ", "Nữ"), ("Khác", "Khác")],
                        default="Nam",
                        max_length=10,
                        verbose_name="Người đại diện - Giới tính",
                    ),
                ),
                (
                    "nguoi_dai_dien_nghe_nghiep",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Người đại diện - Nghề nghiệp",
                    ),
                ),
                (
                    "nguoi_dai_dien_loai_giay_to",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CCCD", "Căn cước công dân"),
                            ("CCCD_CHIP", "CCCD gắn chip điện tử"),
                            ("CMND", "Chứng minh nhân dân"),
                            ("HC", "Hộ chiếu"),
                        ],
                        default="CCCD",
                        max_length=20,
                        verbose_name="Người đại diện - Loại giấy tờ",
                    ),
                ),
                (
                    "nguoi_dai_dien_so_cccd",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Người đại diện - Số CCCD/CMND",
                    ),
                ),
                (
                    "nguoi_dai_dien_ngay_cap",
                    models.DateField(
                        blank=True, null=True, verbose_name="Người đại diện - Ngày cấp"
                    ),
                ),
                (
                    "nguoi_dai_dien_noi_cap",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Người đại diện - Nơi cấp",
                    ),
                ),
                (
                    "nguoi_dai_dien_ngay_het_han",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Người đại diện - Ngày hết hạn",
                    ),
                ),
                (
                    "nguoi_dai_dien_noi_o_hien_tai",
                    models.TextField(
                        blank=True, verbose_name="Người đại diện - Nơi ở hiện tại"
                    ),
                ),
                (
                    "ke_toan_truong_ho_ten",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Kế toán trưởng - Họ và tên",
                    ),
                ),
                (
                    "ke_toan_truong_ngay_sinh",
                    models.DateField(
                        blank=True, null=True, verbose_name="Kế toán trưởng - Ngày sinh"
                    ),
                ),
                (
                    "ke_toan_truong_gioi_tinh",
                    models.CharField(
                        blank=True,
                        choices=[("Nam", "Nam"), ("Nữ", "Nữ"), ("Khác", "Khác")],
                        default="Nam",
                        max_length=10,
                        verbose_name="Kế toán trưởng - Giới tính",
                    ),
                ),
                (
                    "ke_toan_truong_nghe_nghiep",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Kế toán trưởng - Nghề nghiệp",
                    ),
                ),
                (
                    "ke_toan_truong_loai_giay_to",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CCCD", "Căn cước công dân"),
                            ("CCCD_CHIP", "CCCD gắn chip điện tử"),
                            ("CMND", "Chứng minh nhân dân"),
                            ("HC", "Hộ chiếu"),
                        ],
                        default="CCCD",
                        max_length=20,
                        verbose_name="Kế toán trưởng - Loại giấy tờ",
                    ),
                ),
                (
                    "ke_toan_truong_so_cccd",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Kế toán trưởng - Số CCCD/CMND",
                    ),
                ),
                (
                    "ke_toan_truong_ngay_cap",
                    models.DateField(
                        blank=True, null=True, verbose_name="Kế toán trưởng - Ngày cấp"
                    ),
                ),
                (
                    "ke_toan_truong_noi_cap",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Kế toán trưởng - Nơi cấp",
                    ),
                ),
                (
                    "ke_toan_truong_ngay_het_han",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Kế toán trưởng - Ngày hết hạn",
                    ),
                ),
                (
                    "ke_toan_truong_noi_o_hien_tai",
                    models.TextField(
                        blank=True, verbose_name="Kế toán trưởng - Nơi ở hiện tại"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
            ],
            options={
                "verbose_name": "Doanh nghiệp",
                "verbose_name_plural": "Doanh nghiệp",
                "ordering": ["ten_doanh_nghiep"],
            },
        ),
    ]
