# Generated by Django 5.2.7 on 2025-11-27 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0029_userprofile_certificate_code_and_more'),
        ('templates_app', '0031_alter_category_visible_field_groups'),
        ('templates_app', '0033_atm_atmdiscrepancy_atmmanagementboard_and_more'),
    ]

    operations = [
    ]
