# Generated by Django 5.2.7 on 2025-12-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates_app", "0035_business"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="ke_toan_truong_dien_thoai",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Kế toán trưởng - Điện thoại"
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="nguoi_dai_dien_dien_thoai",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Người đại diện - Điện thoại"
            ),
        ),
    ]
