# Generated by Claude Code on 2025-12-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates_app", "0036_business_ke_toan_truong_dien_thoai_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfig",
            name="gcndkdn",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Giấy chứng nhận đăng ký kinh doanh"
            ),
        ),
        migrations.AddField(
            model_name="globalconfig",
            name="mst_chi_nhanh",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Mã số thuế chi nhánh"
            ),
        ),
        migrations.AddField(
            model_name="globalconfig",
            name="nguoi_dai_dien",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Người đại diện"
            ),
        ),
        migrations.AddField(
            model_name="globalconfig",
            name="chuc_vu",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Chức vụ"
            ),
        ),
        migrations.AddField(
            model_name="globalconfig",
            name="so_uy_quyen",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Số uỷ quyền"
            ),
        ),
    ]
