# Generated by Django 5.2.7 on 2025-12-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates_app", "0036_business_ke_toan_truong_dien_thoai_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="business",
            name="id",
        ),
        migrations.AddField(
            model_name="business",
            name="ten_bang_hieu",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Tên bảng hiệu"
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="cif",
            field=models.CharField(
                blank=True, db_index=True, max_length=20, verbose_name="Mã CIF"
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="so_gcn",
            field=models.CharField(
                max_length=50,
                primary_key=True,
                serialize=False,
                verbose_name="Số GCN đăng ký DN/Giấy ĐKKD/QĐ thành lập",
            ),
        ),
    ]
