# Generated by Django 5.2.7 on 2025-12-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates_app", "0036_business_ke_toan_truong_dien_thoai_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="ten_bang_hieu",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Tên bảng hiệu"
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="cif",
            field=models.CharField(
                blank=True, db_index=True, max_length=20, verbose_name="Mã CIF"
            ),
        ),
    ]
