# Generated by Django 5.2.7 on 2025-12-11 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0034_alter_template_file'),
        ('templates_app', '0036_merge_20251128_0538'),
    ]

    operations = [
    ]
