# Generated by Django 5.2.7 on 2025-12-13 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0037_merge_20251211_2106'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=200, verbose_name='Tên mẫu biểu')),
                ('customer_name', models.CharField(blank=True, max_length=200, verbose_name='Tên khách hàng')),
                ('customer_cmnd', models.CharField(blank=True, max_length=20, verbose_name='CMND khách hàng')),
                ('created_by_username', models.CharField(max_length=150, verbose_name='Username người tạo')),
                ('file_name', models.CharField(max_length=500, verbose_name='Tên file')),
                ('file_size', models.IntegerField(default=0, verbose_name='Kích thước file (bytes)')),
                ('data_snapshot', models.JSONField(default=dict, verbose_name='Dữ liệu đã điền')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_histories', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_histories', to='templates_app.customer', verbose_name='Khách hàng')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_histories', to='templates_app.template', verbose_name='Mẫu biểu')),
            ],
            options={
                'verbose_name': 'Lịch sử tạo mẫu biểu',
                'verbose_name_plural': 'Lịch sử tạo mẫu biểu',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='templates_a_created_32af2f_idx'), models.Index(fields=['created_by', '-created_at'], name='templates_a_created_d62150_idx'), models.Index(fields=['customer', '-created_at'], name='templates_a_custome_541906_idx'), models.Index(fields=['template', '-created_at'], name='templates_a_templat_f2ffbc_idx')],
            },
        ),
    ]
