# Generated by Claude Code on 2025-12-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates_app", "0037_add_branch_config_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfig",
            name="ngay_uy_quyen",
            field=models.DateField(
                blank=True, null=True, verbose_name="Ngày uỷ quyền"
            ),
        ),
    ]
