# Generated by Claude Code on 2025-12-18 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("templates_app", "0038_globalconfig_ngay_uy_quyen"),
    ]

    operations = [
        migrations.CreateModel(
            name="BranchConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "branch_code",
                    models.CharField(
                        help_text="Ví dụ: HOI_SO, PGD_LANG_TRON, PGD_P1",
                        max_length=50,
                        unique=True,
                        verbose_name="Mã đơn vị",
                    ),
                ),
                (
                    "branch_type",
                    models.CharField(
                        choices=[
                            ("CHI_NHANH", "Chi nhánh"),
                            ("PGD", "Phòng giao dịch"),
                            ("HOI_SO", "Hội sở"),
                        ],
                        default="CHI_NHANH",
                        max_length=20,
                        verbose_name="Loại đơn vị",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Kích hoạt")),
                (
                    "ten_chi_nhanh",
                    models.CharField(max_length=200, verbose_name="Tên chi nhánh"),
                ),
                (
                    "ten_chi_nhanh_hoa",
                    models.CharField(max_length=200, verbose_name="Tên chi nhánh (IN HOA)"),
                ),
                (
                    "ma_chi_nhanh",
                    models.CharField(blank=True, max_length=20, verbose_name="Mã chi nhánh"),
                ),
                (
                    "mst",
                    models.CharField(blank=True, max_length=50, verbose_name="Mã số thuế"),
                ),
                (
                    "gcndkdn",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Giấy chứng nhận đăng ký kinh doanh",
                    ),
                ),
                (
                    "mst_chi_nhanh",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Mã số thuế chi nhánh"
                    ),
                ),
                (
                    "dia_chi_chi_nhanh",
                    models.TextField(blank=True, verbose_name="Địa chỉ chi nhánh"),
                ),
                (
                    "dien_thoai_chi_nhanh",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Điện thoại chi nhánh"
                    ),
                ),
                (
                    "so_fax",
                    models.CharField(blank=True, max_length=50, verbose_name="Số Fax"),
                ),
                (
                    "dia_danh",
                    models.CharField(
                        blank=True,
                        help_text="Ví dụ: Bạc Liêu, Đồng Tháp",
                        max_length=200,
                        verbose_name="Địa danh",
                    ),
                ),
                (
                    "nguoi_dai_dien",
                    models.CharField(blank=True, max_length=200, verbose_name="Người đại diện"),
                ),
                (
                    "chuc_vu",
                    models.CharField(blank=True, max_length=200, verbose_name="Chức vụ"),
                ),
                (
                    "so_uy_quyen",
                    models.CharField(blank=True, max_length=100, verbose_name="Số uỷ quyền"),
                ),
                (
                    "ngay_uy_quyen",
                    models.DateField(blank=True, null=True, verbose_name="Ngày uỷ quyền"),
                ),
                (
                    "giao_dich_vien",
                    models.CharField(blank=True, max_length=200, verbose_name="Giao dịch viên"),
                ),
                (
                    "kiem_soat_vien",
                    models.CharField(blank=True, max_length=200, verbose_name="Kiểm soát viên"),
                ),
                (
                    "giam_doc",
                    models.CharField(blank=True, max_length=200, verbose_name="Giám đốc"),
                ),
                (
                    "custom_variables",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Các biến tùy chỉnh riêng cho chi nhánh này",
                        verbose_name="Biến tùy chỉnh riêng",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người cập nhật",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cấu hình Chi nhánh",
                "verbose_name_plural": "Cấu hình Chi nhánh",
                "ordering": ["branch_code"],
            },
        ),
    ]
