# Generated by Django 5.2.7 on 2025-12-17 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0038_documenthistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentHistory',
        ),
    ]
