# Generated by Django 5.2.7 on 2025-12-17 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0035_business'),
        ('templates_app', '0039_delete_documenthistory'),
    ]

    operations = [
    ]
