# Generated by Claude Code on 2025-12-18 09:45
# Data migration to populate BranchConfig with sample data

from django.db import migrations


def create_sample_branch_configs(apps, schema_editor):
    """
    Tạo dữ liệu mẫu cho BranchConfig
    - Chi nhánh Giá Rai Bạc Liêu (HOI_SO)
    - Phòng Giao dịch Láng Tròn (PGD_LANG_TRON)
    - Phòng Giao dịch Phường 1 (PGD_P1)
    """
    BranchConfig = apps.get_model('templates_app', 'BranchConfig')

    # 1. Chi nhánh Giá Rai Bạc Liêu (Hội sở)
    BranchConfig.objects.get_or_create(
        branch_code='HOI_SO',
        defaults={
            'branch_type': 'HOI_SO',
            'ten_chi_nhanh': 'Chi nhánh Giá Rai Bạc Liêu',
            'ten_chi_nhanh_hoa': 'CHI NHÁNH GIÁ RAI BẠC LIÊU',
            'ma_chi_nhanh': '100',
            'mst': '0123456789',
            'gcndkdn': '0123456789',
            'dia_chi_chi_nhanh': '123 Đường ABC, Phường Giá Rai, TP. Bạc Liêu',
            'dien_thoai_chi_nhanh': '0291.3822468',
            'so_fax': '0291.3822469',
            'dia_danh': 'Bạc Liêu',
            'nguoi_dai_dien': 'Nguyễn Văn A',
            'chuc_vu': 'Giám đốc Chi nhánh',
            'so_uy_quyen': '123/UQ-HĐQT',
            'giao_dich_vien': 'Trần Thị B',
            'kiem_soat_vien': 'Lê Văn C',
            'giam_doc': 'Nguyễn Văn A',
            'is_active': True,
        }
    )

    # 2. Phòng Giao dịch Láng Tròn
    BranchConfig.objects.get_or_create(
        branch_code='PGD_LANG_TRON',
        defaults={
            'branch_type': 'PGD',
            'ten_chi_nhanh': 'Phòng Giao dịch Láng Tròn',
            'ten_chi_nhanh_hoa': 'PHÒNG GIAO DỊCH LÁNG TRÒN',
            'ma_chi_nhanh': '101',
            'mst': '0123456789-001',
            'gcndkdn': '0123456789',
            'mst_chi_nhanh': '0123456789-001',
            'dia_chi_chi_nhanh': '456 Đường DEF, Xã Láng Tròn, Huyện Giá Rai, Tỉnh Bạc Liêu',
            'dien_thoai_chi_nhanh': '0291.3822470',
            'so_fax': '0291.3822471',
            'dia_danh': 'Bạc Liêu',
            'nguoi_dai_dien': 'Phạm Thị D',
            'chuc_vu': 'Giám đốc Phòng Giao dịch',
            'so_uy_quyen': '456/UQ-CN',
            'giao_dich_vien': 'Hoàng Văn E',
            'kiem_soat_vien': 'Võ Thị F',
            'giam_doc': 'Phạm Thị D',
            'is_active': True,
        }
    )

    # 3. Phòng Giao dịch Phường 1
    BranchConfig.objects.get_or_create(
        branch_code='PGD_P1',
        defaults={
            'branch_type': 'PGD',
            'ten_chi_nhanh': 'Phòng Giao dịch Phường 1',
            'ten_chi_nhanh_hoa': 'PHÒNG GIAO DỊCH PHƯỜNG 1',
            'ma_chi_nhanh': '102',
            'mst': '0123456789-002',
            'gcndkdn': '0123456789',
            'mst_chi_nhanh': '0123456789-002',
            'dia_chi_chi_nhanh': '789 Đường GHI, Phường 1, TP. Bạc Liêu',
            'dien_thoai_chi_nhanh': '0291.3822472',
            'so_fax': '0291.3822473',
            'dia_danh': 'Bạc Liêu',
            'nguoi_dai_dien': 'Đặng Văn G',
            'chuc_vu': 'Giám đốc Phòng Giao dịch',
            'so_uy_quyen': '789/UQ-CN',
            'giao_dich_vien': 'Mai Thị H',
            'kiem_soat_vien': 'Bùi Văn I',
            'giam_doc': 'Đặng Văn G',
            'is_active': True,
        }
    )


def reverse_populate(apps, schema_editor):
    """Xóa dữ liệu mẫu khi rollback migration"""
    BranchConfig = apps.get_model('templates_app', 'BranchConfig')
    BranchConfig.objects.filter(
        branch_code__in=['HOI_SO', 'PGD_LANG_TRON', 'PGD_P1']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("templates_app", "0039_branchconfig"),
    ]

    operations = [
        migrations.RunPython(create_sample_branch_configs, reverse_populate),
    ]
