# Generated by Django 5.2.7 on 2025-12-20 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("templates_app", "0037_business_ten_bang_hieu_alter_business_cif"),
        ("templates_app", "0040_populate_branch_configs"),
    ]

    operations = []
