# Generated by Django 5.2.7 on 2025-12-18 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0036_business_ke_toan_truong_dien_thoai_and_more'),
        ('templates_app', '0040_merge_0035_business_0039_delete_documenthistory'),
    ]

    operations = [
    ]
