# Generated by Django 5.2.7 on 2025-12-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates_app", "0041_merge_20251221_0424"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="img_id_back",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="customer_docs/%Y/%m/",
                verbose_name="Ảnh mặt sau CCCD",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="img_id_front",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="customer_docs/%Y/%m/",
                verbose_name="Ảnh mặt trước CCCD",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="img_portrait",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="customer_docs/%Y/%m/",
                verbose_name="Ảnh chân dung",
            ),
        ),
    ]
