# Generated by Django 5.2.7 on 2025-12-18 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0040_populate_branch_configs'),
        ('templates_app', '0041_merge_20251218_1341'),
    ]

    operations = [
    ]
