# Generated by Django 5.2.7 on 2025-12-23 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0042_customer_img_id_back_customer_img_id_front_and_more'),
        ('templates_app', '0042_merge_20251218_1755'),
    ]

    operations = [
    ]
