# Generated by Django 5.2.7 on 2026-01-06 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates_app", "0043_merge_20251223_2347"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ATMReportUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(max_length=255, verbose_name="Tên file"),
                ),
                ("report_period", models.DateField(verbose_name="Kỳ báo cáo")),
                (
                    "upload_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày upload"),
                ),
                (
                    "record_count",
                    models.IntegerField(default=0, verbose_name="Số lượng bản ghi"),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người upload",
                    ),
                ),
            ],
            options={
                "verbose_name": "File báo cáo ATM",
                "verbose_name_plural": "Lịch sử upload báo cáo ATM",
                "ordering": ["-report_period", "-upload_date"],
                "unique_together": {("report_period",)},
            },
        ),
        migrations.CreateModel(
            name="ATMTransactionReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "branch_code",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="Mã chi nhánh"
                    ),
                ),
                (
                    "atm_no",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="Số hiệu ATM"
                    ),
                ),
                (
                    "tx_code",
                    models.CharField(max_length=50, verbose_name="Mã giao dịch"),
                ),
                (
                    "tx_count",
                    models.IntegerField(default=0, verbose_name="Số lượng giao dịch"),
                ),
                (
                    "tx_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Số tiền giao dịch",
                    ),
                ),
                (
                    "tx_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Phí giao dịch",
                    ),
                ),
                (
                    "vatamt",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=20, verbose_name="VAT"
                    ),
                ),
                (
                    "report_period",
                    models.DateField(db_index=True, verbose_name="Kỳ báo cáo"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="templates_app.atmreportupload",
                        verbose_name="File upload",
                    ),
                ),
            ],
            options={
                "verbose_name": "Giao dịch ATM",
                "verbose_name_plural": "Báo cáo giao dịch ATM",
                "ordering": ["-report_period", "atm_no"],
                "indexes": [
                    models.Index(
                        fields=["report_period", "atm_no"],
                        name="templates_a_report__8885ca_idx",
                    ),
                    models.Index(
                        fields=["report_period", "branch_code"],
                        name="templates_a_report__035481_idx",
                    ),
                ],
            },
        ),
    ]
