# Generated by Django 5.2.10 on 2026-01-31 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates_app", "0044_atmreportupload_atmtransactionreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, verbose_name="Tiêu đề chương trình"
                    ),
                ),
                ("content", models.TextField(verbose_name="Nội dung chi tiết")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="promotions/",
                        verbose_name="Hình ảnh banner",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày đăng"),
                ),
                ("start_date", models.DateField(verbose_name="Ngày bắt đầu hiệu lực")),
                ("end_date", models.DateField(verbose_name="Ngày hết hạn")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Hiển thị"),
                ),
            ],
            options={
                "verbose_name": "Chương trình khuyến mãi",
                "verbose_name_plural": "Chương trình khuyến mãi",
                "ordering": ["-created_at"],
            },
        ),
    ]
