# Generated by Django 5.2.7 on 2026-04-10 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0045_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DongMoTaiKhoanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_month', models.DateField(verbose_name='Kỳ báo cáo')),
                ('tong_mo', models.IntegerField(default=0, verbose_name='Tổng mở TK')),
                ('ca_nhan_count', models.IntegerField(default=0, verbose_name='Cá nhân')),
                ('to_chuc_count', models.IntegerField(default=0, verbose_name='Tổ chức')),
                ('the_mien_phi_count', models.IntegerField(default=0, verbose_name='Thẻ miễn phí')),
                ('hssv_count', models.IntegerField(default=0, verbose_name='HSSV')),
                ('dong_tk_count', models.IntegerField(default=0, verbose_name='Đóng TK')),
                ('dong_he_thong_count', models.IntegerField(default=0, verbose_name='Hệ thống tự đóng')),
                ('dong_tai_quay_count', models.IntegerField(default=0, verbose_name='Đóng tại quầy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lịch sử Đóng/Mở tài khoản',
                'verbose_name_plural': 'Lịch sử Đóng/Mở tài khoản',
                'ordering': ['-report_month'],
                'unique_together': {('report_month',)},
            },
        ),
    ]
