# Generated by Django 5.2.7 on 2026-04-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0046_add_dongmotaikhoan_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên chương trình')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='Đường dẫn / Link')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
            ],
            options={
                'verbose_name': 'Chương trình',
                'verbose_name_plural': 'Danh sách chương trình',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Địa chỉ IP'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ipcas_user',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tài khoản IPCAS'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mac_address',
            field=models.CharField(blank=True, help_text='Định dạng: XX:XX:XX:XX:XX:XX', max_length=17, verbose_name='Địa chỉ MAC'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='branch',
            field=models.CharField(blank=True, help_text='Mã đơn vị (phải khớp với BranchConfig.branch_code)', max_length=50, verbose_name='Chi nhánh'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='app_permissions',
            field=models.ManyToManyField(blank=True, related_name='authorized_users', to='templates_app.appprogram', verbose_name='Chương trình được cấp phép'),
        ),
    ]
