# Generated by Django 5.2.7 on 2026-04-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0047_add_appprogram_and_userprofile_system_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmmanagementboard',
            name='position',
            field=models.CharField(choices=[('team_leader', 'Trưởng Ban'), ('treasury_head', 'Trưởng phòng KTNQ'), ('atm_officer', 'Cán bộ phụ trách ATM')], max_length=50, verbose_name='Chức vụ'),
        ),
    ]
