# Generated by Django 5.2.7 on 2026-04-24 08:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0048_atmmanagementboard_remove_unique_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='atmdiscrepancy',
            name='group_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name='Mã nhóm chu kỳ'),
        ),
    ]
