# Generated by Django 5.2.7 on 2026-05-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0049_atmdiscrepancy_add_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dongmotaikhoanhistory',
            name='dong_ca_nhan_count',
            field=models.IntegerField(default=0, verbose_name='Đóng TK - Cá nhân'),
        ),
        migrations.AddField(
            model_name='dongmotaikhoanhistory',
            name='dong_ca_nhan_tai_quay',
            field=models.IntegerField(default=0, verbose_name='Đóng TK - Cá nhân tại quầy'),
        ),
        migrations.AddField(
            model_name='dongmotaikhoanhistory',
            name='dong_ca_nhan_tu_dong',
            field=models.IntegerField(default=0, verbose_name='Đóng TK - Cá nhân tự động'),
        ),
        migrations.AddField(
            model_name='dongmotaikhoanhistory',
            name='dong_to_chuc_count',
            field=models.IntegerField(default=0, verbose_name='Đóng TK - Tổ chức'),
        ),
        migrations.AddField(
            model_name='dongmotaikhoanhistory',
            name='dong_to_chuc_tai_quay',
            field=models.IntegerField(default=0, verbose_name='Đóng TK - Tổ chức tại quầy'),
        ),
        migrations.AddField(
            model_name='dongmotaikhoanhistory',
            name='dong_to_chuc_tu_dong',
            field=models.IntegerField(default=0, verbose_name='Đóng TK - Tổ chức tự động'),
        ),
    ]
