# Generated by Django 5.2.7 on 2026-06-22 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0050_dongmotaikhoanhistory_dong_ca_nhan_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atmmanagementboard',
            name='decision_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày quyết định thành lập'),
        ),
        migrations.AddField(
            model_name='atmmanagementboard',
            name='decision_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Số quyết định'),
        ),
    ]
