# Generated by Django 5.2.7 on 2026-06-26 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0051_atmmanagementboard_add_decision_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FTPConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_goi', models.CharField(max_length=50, verbose_name='Mã gói ưu đãi')),
                ('ten_goi', models.CharField(max_length=200, verbose_name='Tên gói')),
                ('ftp_pct', models.FloatField(default=5.0, verbose_name='FTP % bán')),
                ('bien_do_pct', models.FloatField(default=0.0, verbose_name='Biên độ hỗ trợ %')),
                ('cach_tinh', models.CharField(choices=[('SPRD-FTP+DIEU_CHINH', 'NIM = Lãi suất - FTP + Biên độ'), ('SPRD-FTP-DIEU_CHINH', 'NIM = Lãi suất - FTP - Biên độ'), ('SPRD-FTP', 'NIM = Lãi suất - FTP (không biên độ)'), ('NIM_CO_DINH', 'NIM cố định')], default='SPRD-FTP+DIEU_CHINH', max_length=30, verbose_name='Công thức NIM')),
                ('nim_co_dinh_pct', models.FloatField(default=0.0, verbose_name='NIM cố định %')),
                ('loai_kh', models.CharField(choices=[('Tất cả', 'Tất cả'), ('Cá nhân', 'Cá nhân'), ('Tổ chức', 'Tổ chức')], default='Tất cả', max_length=10, verbose_name='Loại khách hàng')),
                ('is_default', models.BooleanField(default=False, help_text='Đặt một bản ghi làm mặc định (FTP chung khi khoản vay không có mã gói).', verbose_name='Dùng khi không khớp gói')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cấu hình FTP/NIM',
                'verbose_name_plural': 'Cấu hình FTP/NIM',
                'ordering': ['ma_goi'],
            },
        ),
        migrations.CreateModel(
            name='TDSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_date', models.DateField(db_index=True, verbose_name='Ngày dữ liệu file MSIT80')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm upload')),
                ('file_name', models.CharField(blank=True, max_length=200, verbose_name='Tên file gốc')),
                ('so_lds', models.IntegerField(default=0, verbose_name='Số LDS')),
                ('so_kh', models.IntegerField(default=0, verbose_name='Số KH')),
                ('so_hd', models.IntegerField(default=0, verbose_name='Số HĐ tín dụng')),
                ('tong_du_no', models.BigIntegerField(default=0, verbose_name='Tổng dư nợ (đồng)')),
                ('qua_han', models.IntegerField(default=0, verbose_name='Số khoản quá hạn')),
                ('nhom2', models.IntegerField(default=0, verbose_name='Nhóm 2')),
                ('nhom35', models.IntegerField(default=0, verbose_name='Nhóm 3-5')),
                ('kh_dac_biet', models.IntegerField(default=0, verbose_name='KH đặc biệt')),
                ('summary_json', models.JSONField(default=dict, verbose_name='JSON tóm tắt phân tích')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='td_snapshots', to=settings.AUTH_USER_MODEL, verbose_name='Người upload')),
            ],
            options={
                'verbose_name': 'Snapshot phân tích tín dụng',
                'verbose_name_plural': 'Snapshot phân tích tín dụng',
                'ordering': ['-file_date', '-uploaded_at'],
            },
        ),
    ]
