# Generated by Django 5.2.7 on 2026-07-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0052_td_ftp_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='atmmanagementboard',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Số tài khoản'),
        ),
        migrations.AddField(
            model_name='atmmanagementboard',
            name='effective_from',
            field=models.DateField(blank=True, null=True, verbose_name='Hiệu lực từ ngày'),
        ),
        migrations.AddField(
            model_name='atmmanagementboard',
            name='effective_to',
            field=models.DateField(blank=True, null=True, verbose_name='Hiệu lực đến ngày (bỏ trống nếu đang đương nhiệm)'),
        ),
    ]
