# Generated by Django 5.2.7 on 2026-07-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0053_atmmanagementboard_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Số tài khoản'),
        ),
    ]
