# Generated by Django 5.2.7 on 2026-07-16 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0054_person_account_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HDVRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_kh', models.CharField(max_length=200, verbose_name='Tên KH/Tên KHPN')),
                ('sdt', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('cccd', models.CharField(db_index=True, max_length=30, verbose_name='CCCD/GPĐKKD/GCNĐT/Mã số DN/MST')),
                ('ngay_dk_huy_dong', models.DateField(db_index=True, verbose_name='Ngày ĐK huy động')),
                ('so_tien', models.BigIntegerField(verbose_name='Số tiền')),
                ('loai_tien', models.CharField(default='VND', max_length=10, verbose_name='Loại tiền')),
                ('ma_can_bo', models.CharField(db_index=True, max_length=30, verbose_name='Mã cán bộ')),
                ('chi_nhanh', models.CharField(blank=True, max_length=20, verbose_name='Chi nhánh')),
                ('ngay_gui_dk', models.DateTimeField(auto_now_add=True, verbose_name='Ngày gửi đăng ký')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('user_dk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hdv_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Người đăng ký')),
            ],
            options={
                'verbose_name': 'Đăng ký chỉ tiêu huy động vốn',
                'verbose_name_plural': 'Đăng ký chỉ tiêu huy động vốn',
                'ordering': ['-ngay_gui_dk'],
            },
        ),
    ]
