# Generated by Django 5.2.7 on 2026-07-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0055_hdv_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='hdvregistration',
            name='ten_can_bo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tên cán bộ'),
        ),
    ]
