# Generated by Django 5.2.7 on 2026-07-16 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0056_hdv_registration_ten_can_bo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HDVImportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_cn', models.CharField(blank=True, max_length=20, verbose_name='Mã chi nhánh')),
                ('ma_kh', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='Mã khách hàng')),
                ('ten_kh', models.CharField(max_length=200, verbose_name='Tên khách hàng')),
                ('id_number', models.CharField(db_index=True, max_length=30, verbose_name='CCCD/GPĐKKD/GCNĐT/Mã số DN/MST')),
                ('ccy', models.CharField(default='VND', max_length=10, verbose_name='Loại tiền')),
                ('current_balance', models.BigIntegerField(default=0, verbose_name='Số dư hiện tại')),
                ('so_tai_khoan', models.CharField(max_length=30, unique=True, verbose_name='Số tài khoản')),
                ('opening_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Ngày mở/gửi')),
                ('maturity_date', models.DateField(blank=True, null=True, verbose_name='Ngày đáo hạn')),
                ('month_term', models.IntegerField(default=0, verbose_name='Kỳ hạn (tháng)')),
                ('account_status', models.CharField(blank=True, max_length=20, verbose_name='Trạng thái sổ')),
                ('employee_number', models.CharField(db_index=True, max_length=30, verbose_name='Mã cán bộ')),
                ('employee_name', models.CharField(blank=True, max_length=200, verbose_name='Tên cán bộ')),
                ('uploaded_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hdv_imports', to=settings.AUTH_USER_MODEL, verbose_name='Người upload')),
            ],
            options={
                'verbose_name': 'Bản ghi HĐV import từ IPCAS',
                'verbose_name_plural': 'Bản ghi HĐV import từ IPCAS',
                'ordering': ['-opening_date'],
            },
        ),
    ]
