# Generated by Django 5.2.7 on 2026-07-16 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0057_hdv_import_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDutySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Ngày trực')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('driver', models.ForeignKey(limit_choices_to={'person_type': 'driver'}, on_delete=django.db.models.deletion.PROTECT, to='templates_app.person', verbose_name='Tài xế trực')),
            ],
            options={
                'verbose_name': 'Lịch trực xe',
                'verbose_name_plural': 'Lịch trực xe',
                'ordering': ['date'],
            },
        ),
    ]
