# Generated by Django 5.2.7 on 2026-07-21 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0058_vehicledutyschedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashPrintConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset_x', models.FloatField(default=0, verbose_name='Dịch chuyển trục X (mm)')),
                ('offset_y', models.FloatField(default=0, verbose_name='Dịch chuyển trục Y (mm)')),
                ('start_y', models.FloatField(default=40.0, verbose_name='Vị trí dòng mệnh giá đầu tiên (mm từ trên)')),
                ('row_spacing', models.FloatField(default=8.0, verbose_name='Khoảng cách giữa các dòng mệnh giá (mm)')),
                ('col_so_to_x', models.FloatField(default=90.0, verbose_name='Vị trí cột Số tờ (mm từ trái)')),
                ('col_thanh_tien_x', models.FloatField(default=130.0, verbose_name='Vị trí cột Thành tiền (mm từ trái)')),
                ('date_x', models.FloatField(default=140.0, verbose_name='Vị trí Ngày - X (mm từ trái)')),
                ('date_y', models.FloatField(default=15.0, verbose_name='Vị trí Ngày - Y (mm từ trên)')),
                ('total_x', models.FloatField(default=130.0, verbose_name='Vị trí Tổng cộng - X (mm từ trái)')),
                ('total_y', models.FloatField(default=115.0, verbose_name='Vị trí Tổng cộng - Y (mm từ trên)')),
                ('font_size', models.FloatField(default=10.0, verbose_name='Cỡ chữ (pt)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cấu hình in bảng kê tiền mặt',
                'verbose_name_plural': 'Cấu hình in bảng kê tiền mặt',
            },
        ),
        migrations.CreateModel(
            name='CashDrawerStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai', models.CharField(choices=[('THU', 'Bảng kê thu'), ('CHI', 'Bảng kê chi'), ('NHAP_QUY', 'Nhập quỹ (GDV chính xuất)'), ('RESET', 'Reset counter (out quỹ)')], max_length=10, verbose_name='Loại')),
                ('ghi_chu', models.CharField(blank=True, max_length=200, verbose_name='Ghi chú')),
                ('chi_tiet', models.JSONField(default=dict, verbose_name='Chi tiết số tờ theo mệnh giá')),
                ('tong_tien', models.BigIntegerField(default=0, verbose_name='Tổng tiền')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Thời gian')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_statements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bảng kê tiền mặt',
                'verbose_name_plural': 'Bảng kê tiền mặt',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashDrawerBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menh_gia', models.IntegerField(verbose_name='Mệnh giá')),
                ('so_to', models.IntegerField(default=0, verbose_name='Số tờ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_drawer_balances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tồn quỹ tiền mặt theo mệnh giá',
                'verbose_name_plural': 'Tồn quỹ tiền mặt theo mệnh giá',
                'ordering': ['-menh_gia'],
                'constraints': [models.UniqueConstraint(fields=('user', 'menh_gia'), name='uniq_cash_balance_user_menhgia')],
            },
        ),
    ]
