# Generated by Django 5.2.7 on 2026-07-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0059_cash_drawer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashprintconfig',
            name='so_tien_chu_x',
            field=models.FloatField(default=20.0, verbose_name='Vị trí Số tiền bằng chữ - X (mm từ trái)'),
        ),
        migrations.AddField(
            model_name='cashprintconfig',
            name='so_tien_chu_y',
            field=models.FloatField(default=125.0, verbose_name='Vị trí Số tiền bằng chữ - Y (mm từ trên)'),
        ),
    ]
