# Generated by Django 5.2.7 on 2026-07-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0060_cash_print_config_so_tien_chu'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashPrintConfigNopTien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset_x', models.FloatField(default=0, verbose_name='Dịch chuyển trục X (mm)')),
                ('offset_y', models.FloatField(default=0, verbose_name='Dịch chuyển trục Y (mm)')),
                ('start_y', models.FloatField(default=40.0, verbose_name='Vị trí dòng mệnh giá đầu tiên (mm từ trên)')),
                ('row_spacing', models.FloatField(default=8.0, verbose_name='Khoảng cách giữa các dòng mệnh giá (mm)')),
                ('col_so_to_x', models.FloatField(default=90.0, verbose_name='Vị trí cột Số tờ (mm từ trái)')),
                ('col_thanh_tien_x', models.FloatField(default=130.0, verbose_name='Vị trí cột Thành tiền (mm từ trái)')),
                ('date_x', models.FloatField(default=140.0, verbose_name='Vị trí Ngày - X (mm từ trái)')),
                ('date_y', models.FloatField(default=15.0, verbose_name='Vị trí Ngày - Y (mm từ trên)')),
                ('total_x', models.FloatField(default=130.0, verbose_name='Vị trí Tổng cộng - X (mm từ trái)')),
                ('total_y', models.FloatField(default=115.0, verbose_name='Vị trí Tổng cộng - Y (mm từ trên)')),
                ('so_tien_chu_x', models.FloatField(default=20.0, verbose_name='Vị trí Số tiền bằng chữ - X (mm từ trái)')),
                ('so_tien_chu_y', models.FloatField(default=125.0, verbose_name='Vị trí Số tiền bằng chữ - Y (mm từ trên)')),
                ('font_size', models.FloatField(default=10.0, verbose_name='Cỡ chữ (pt)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cấu hình in bảng kê trắng (giấy nộp tiền)',
                'verbose_name_plural': 'Cấu hình in bảng kê trắng (giấy nộp tiền)',
            },
        ),
    ]
