# Generated by Django 5.2.7 on 2026-07-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0061_cash_print_config_nop_tien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashdrawerstatement',
            name='loai',
            field=models.CharField(choices=[('THU', 'Bảng kê thu'), ('CHI', 'Bảng kê chi'), ('NHAP_QUY', 'Nhập số tiền tiếp quỹ (thực nhận)'), ('DE_NGHI', 'Đề nghị tiếp quỹ'), ('RESET', 'Reset counter (out quỹ)')], max_length=10, verbose_name='Loại'),
        ),
    ]
