# Generated by Django 5.2.7 on 2026-07-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0062_cash_de_nghi_tiep_quy'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashPrintConfigBangKeChi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset_x', models.FloatField(default=0, verbose_name='Dịch chuyển trục X (mm)')),
                ('offset_y', models.FloatField(default=0, verbose_name='Dịch chuyển trục Y (mm)')),
                ('margin', models.FloatField(default=10.0, verbose_name='Lề trang (mm)')),
                ('title_font_size', models.FloatField(default=14.0, verbose_name='Cỡ chữ tiêu đề (pt)')),
                ('body_font_size', models.FloatField(default=9.0, verbose_name='Cỡ chữ nội dung (pt)')),
                ('row_height', models.FloatField(default=6.5, verbose_name='Chiều cao dòng trong bảng (mm)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cấu hình in Bảng kê Chi',
                'verbose_name_plural': 'Cấu hình in Bảng kê Chi',
            },
        ),
        migrations.CreateModel(
            name='CashPrintConfigBangKeThu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset_x', models.FloatField(default=0, verbose_name='Dịch chuyển trục X (mm)')),
                ('offset_y', models.FloatField(default=0, verbose_name='Dịch chuyển trục Y (mm)')),
                ('margin', models.FloatField(default=10.0, verbose_name='Lề trang (mm)')),
                ('title_font_size', models.FloatField(default=14.0, verbose_name='Cỡ chữ tiêu đề (pt)')),
                ('body_font_size', models.FloatField(default=9.0, verbose_name='Cỡ chữ nội dung (pt)')),
                ('row_height', models.FloatField(default=6.5, verbose_name='Chiều cao dòng trong bảng (mm)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cấu hình in Bảng kê Thu',
                'verbose_name_plural': 'Cấu hình in Bảng kê Thu',
            },
        ),
        migrations.CreateModel(
            name='CashPrintConfigDeNghi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset_x', models.FloatField(default=0, verbose_name='Dịch chuyển trục X (mm)')),
                ('offset_y', models.FloatField(default=0, verbose_name='Dịch chuyển trục Y (mm)')),
                ('margin', models.FloatField(default=10.0, verbose_name='Lề trang (mm)')),
                ('title_font_size', models.FloatField(default=14.0, verbose_name='Cỡ chữ tiêu đề (pt)')),
                ('body_font_size', models.FloatField(default=9.0, verbose_name='Cỡ chữ nội dung (pt)')),
                ('row_height', models.FloatField(default=6.5, verbose_name='Chiều cao dòng trong bảng (mm)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cấu hình in Đề nghị tiếp quỹ',
                'verbose_name_plural': 'Cấu hình in Đề nghị tiếp quỹ',
            },
        ),
    ]
