# Generated by Django 5.2.7 on 2026-07-23 06:38

from django.db import migrations, models


def _bump_untouched_row_height(apps, schema_editor):
    """Chỉ cập nhật các bản ghi còn giữ giá trị mặc định cũ (6.5), không ghi đè
    cấu hình mà người dùng đã tự chỉnh."""
    for model_name in ('CashPrintConfigBangKeThu', 'CashPrintConfigBangKeChi', 'CashPrintConfigDeNghi'):
        model = apps.get_model('templates_app', model_name)
        model.objects.filter(row_height=6.5).update(row_height=5.5)


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0063_cash_print_config_chung_tu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashprintconfigbangkechi',
            name='row_height',
            field=models.FloatField(default=5.5, verbose_name='Chiều cao dòng trong bảng (mm)'),
        ),
        migrations.AlterField(
            model_name='cashprintconfigbangkethu',
            name='row_height',
            field=models.FloatField(default=5.5, verbose_name='Chiều cao dòng trong bảng (mm)'),
        ),
        migrations.AlterField(
            model_name='cashprintconfigdenghi',
            name='row_height',
            field=models.FloatField(default=5.5, verbose_name='Chiều cao dòng trong bảng (mm)'),
        ),
        migrations.RunPython(_bump_untouched_row_height, migrations.RunPython.noop),
    ]
