# Generated by Django 5.2.7 on 2026-07-23 06:52

from django.db import migrations, models


def _bump_untouched_defaults(apps, schema_editor):
    """Chỉ cập nhật các bản ghi còn giữ nguyên giá trị mặc định cũ (bị đè lên nhau),
    không ghi đè cấu hình mà người dùng đã tự canh chỉnh."""
    for model_name in ('CashPrintConfig', 'CashPrintConfigNopTien'):
        model = apps.get_model('templates_app', model_name)
        model.objects.filter(
            start_y=40.0, row_spacing=8.0, total_y=115.0, so_tien_chu_y=125.0,
        ).update(start_y=30.0, row_spacing=7.0, total_y=118.0, so_tien_chu_y=130.0)


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0064_alter_cashprintconfigbangkechi_row_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashprintconfig',
            name='date_x',
        ),
        migrations.RemoveField(
            model_name='cashprintconfig',
            name='date_y',
        ),
        migrations.RemoveField(
            model_name='cashprintconfignoptien',
            name='date_x',
        ),
        migrations.RemoveField(
            model_name='cashprintconfignoptien',
            name='date_y',
        ),
        migrations.AlterField(
            model_name='cashprintconfig',
            name='row_spacing',
            field=models.FloatField(default=7.0, verbose_name='Khoảng cách giữa các dòng mệnh giá (mm)'),
        ),
        migrations.AlterField(
            model_name='cashprintconfig',
            name='so_tien_chu_y',
            field=models.FloatField(default=130.0, verbose_name='Vị trí Số tiền bằng chữ - Y (mm từ trên)'),
        ),
        migrations.AlterField(
            model_name='cashprintconfig',
            name='start_y',
            field=models.FloatField(default=30.0, verbose_name='Vị trí dòng mệnh giá đầu tiên (mm từ trên)'),
        ),
        migrations.AlterField(
            model_name='cashprintconfig',
            name='total_y',
            field=models.FloatField(default=118.0, verbose_name='Vị trí Tổng cộng - Y (mm từ trên)'),
        ),
        migrations.AlterField(
            model_name='cashprintconfignoptien',
            name='row_spacing',
            field=models.FloatField(default=7.0, verbose_name='Khoảng cách giữa các dòng mệnh giá (mm)'),
        ),
        migrations.AlterField(
            model_name='cashprintconfignoptien',
            name='so_tien_chu_y',
            field=models.FloatField(default=130.0, verbose_name='Vị trí Số tiền bằng chữ - Y (mm từ trên)'),
        ),
        migrations.AlterField(
            model_name='cashprintconfignoptien',
            name='start_y',
            field=models.FloatField(default=30.0, verbose_name='Vị trí dòng mệnh giá đầu tiên (mm từ trên)'),
        ),
        migrations.AlterField(
            model_name='cashprintconfignoptien',
            name='total_y',
            field=models.FloatField(default=118.0, verbose_name='Vị trí Tổng cộng - Y (mm từ trên)'),
        ),
        migrations.RunPython(_bump_untouched_defaults, migrations.RunPython.noop),
    ]
