# Generated by Django 5.2.7 on 2026-07-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0066_cashprintconfig_user_cashprintconfigbangkechi_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hdvregistration',
            name='ky_han',
            field=models.CharField(blank=True, choices=[('KKH', 'Không kỳ hạn'), ('1T', '1 tháng'), ('2T', '2 tháng'), ('3T', '3 tháng'), ('6T', '6 tháng'), ('9T', '9 tháng'), ('12T', '12 tháng'), ('13T', '13 tháng'), ('18T', '18 tháng'), ('24T', '24 tháng'), ('36T', '36 tháng')], max_length=10, verbose_name='Kỳ hạn gửi tiết kiệm'),
        ),
        migrations.AlterField(
            model_name='hdvregistration',
            name='ngay_dk_huy_dong',
            field=models.DateField(db_index=True, verbose_name='Ngày dự kiến gửi tiền'),
        ),
    ]
