# Generated by Django 5.2.7 on 2026-07-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0067_hdvregistration_ky_han_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hdvregistration',
            name='dia_chi',
            field=models.CharField(blank=True, max_length=300, verbose_name='Địa chỉ'),
        ),
    ]
