# Generated by Django 5.2.7 on 2026-07-24 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0068_hdvregistration_dia_chi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanDoiUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày upload')),
                ('file_name', models.CharField(max_length=255, verbose_name='Tên file')),
                ('tt_trong_nuoc', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='1.1 Thanh toán trong nước')),
                ('tt_quoc_te', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='1.2 Thanh toán quốc tế')),
                ('kieu_hoi', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='1.3 Dịch vụ kiều hối')),
                ('dich_vu_the', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='1.4 Dịch vụ thẻ')),
                ('e_banking', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='1.5 E-Banking')),
                ('uy_thac_dai_ly', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='1.6 Ủy thác và đại lý')),
                ('bao_lanh', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='1.7 Bảo lãnh')),
                ('ngan_quy', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='1.8 Ngân quỹ')),
                ('thu_khac', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='1.9 Thu khác')),
                ('kd_ngoai_hoi', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='1.10 Thu ròng từ KD ngoại hối')),
                ('dieu_tiet_noi_bo', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='III. Điều tiết nội bộ phí dịch vụ')),
                ('tong_doanh_thu', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='IV. Tổng DT Dịch vụ')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='can_doi_uploads', to=settings.AUTH_USER_MODEL, verbose_name='Người upload')),
            ],
            options={
                'verbose_name': 'Đọc Cân đối',
                'verbose_name_plural': 'Đọc Cân đối',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
