# Generated by Django 5.2.7 on 2026-08-02 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0069_candoiupload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_kh', models.CharField(max_length=200, verbose_name='Tên khách hàng')),
                ('so_tai_khoan', models.CharField(db_index=True, max_length=30, verbose_name='Số tài khoản')),
                ('ten_cua_hang', models.CharField(blank=True, max_length=200, verbose_name='Tên cửa hàng')),
                ('ten_can_bo', models.CharField(blank=True, max_length=200, verbose_name='Tên cán bộ đăng ký')),
                ('phong_giao_dich', models.CharField(blank=True, max_length=200, verbose_name='Phòng giao dịch')),
                ('ngay_dang_ky', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày đăng ký')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('user_dk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Người đăng ký')),
            ],
            options={
                'verbose_name': 'Đăng ký bản QR',
                'verbose_name_plural': 'Đăng ký bản QR',
                'ordering': ['-ngay_dang_ky'],
            },
        ),
    ]
