# Generated by Django 5.2.7 on 2026-08-02 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0070_qrregistration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qrregistration',
            options={'ordering': ['-ngay_dang_ky'], 'verbose_name': 'Đăng ký bảng QR', 'verbose_name_plural': 'Đăng ký bảng QR'},
        ),
        migrations.AlterField(
            model_name='qrregistration',
            name='ten_cua_hang',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tên cửa hàng (nếu có)'),
        ),
    ]
