# Generated by Django 5.2.7 on 2026-08-04 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0071_alter_qrregistration_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hdvregistration',
            name='ngay_add_chi_tieu',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày giờ add chỉ tiêu'),
        ),
        migrations.AddField(
            model_name='hdvregistration',
            name='ngay_duyet',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày giờ phê duyệt'),
        ),
        migrations.AddField(
            model_name='hdvregistration',
            name='nguoi_add_chi_tieu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hdv_da_add_chi_tieu', to=settings.AUTH_USER_MODEL, verbose_name='Người add chỉ tiêu'),
        ),
        migrations.AddField(
            model_name='hdvregistration',
            name='nguoi_duyet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hdv_da_duyet', to=settings.AUTH_USER_MODEL, verbose_name='Người phê duyệt'),
        ),
    ]
