# Generated by Django 5.2.7 on 2026-08-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0072_hdvregistration_ngay_add_chi_tieu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hdvregistration',
            name='loai_giao_dich',
            field=models.CharField(choices=[('GUI_MOI', 'Gửi mới'), ('DOI_NHAP_GUI_THEM', 'Đổi/Nhập/gửi thêm sổ')], default='GUI_MOI', max_length=20, verbose_name='Loại giao dịch'),
        ),
    ]
