# Generated by Django 5.2.7 on 2026-09-30 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0073_hdvregistration_loai_giao_dich'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='csp_cuser',
            field=models.CharField(blank=True, help_text='VD: 7202chieutt — dùng để đối chiếu file phát hành thẻ CSP', max_length=100, verbose_name='Tài khoản phát hành thẻ CSP'),
        ),
        migrations.CreateModel(
            name='SPDVKpiRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('THE', 'Số lượng thẻ'), ('AGRIBANK_PLUS', 'Agribank Plus')], max_length=20, verbose_name='Chỉ tiêu')),
                ('year', models.IntegerField(verbose_name='Năm')),
                ('month', models.IntegerField(verbose_name='Tháng')),
                ('quantity', models.IntegerField(default=0, verbose_name='Số lượng đạt được')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spdv_kpi_records_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người import')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spdv_kpi_records', to=settings.AUTH_USER_MODEL, verbose_name='Giao dịch viên')),
            ],
            options={
                'verbose_name': 'Kết quả chỉ tiêu SPDV',
                'verbose_name_plural': 'Kết quả chỉ tiêu SPDV',
                'ordering': ['-year', '-month', 'user'],
                'unique_together': {('user', 'metric_type', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='SPDVKpiTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('THE', 'Số lượng thẻ'), ('AGRIBANK_PLUS', 'Agribank Plus')], max_length=20, verbose_name='Chỉ tiêu')),
                ('year', models.IntegerField(verbose_name='Năm')),
                ('month', models.IntegerField(verbose_name='Tháng')),
                ('target_quantity', models.IntegerField(default=0, verbose_name='Số lượng chỉ tiêu giao')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spdv_kpi_targets_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người đặt chỉ tiêu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spdv_kpi_targets', to=settings.AUTH_USER_MODEL, verbose_name='Giao dịch viên')),
            ],
            options={
                'verbose_name': 'Chỉ tiêu SPDV',
                'verbose_name_plural': 'Chỉ tiêu SPDV',
                'ordering': ['-year', '-month', 'user'],
                'unique_together': {('user', 'metric_type', 'year', 'month')},
            },
        ),
    ]
