# Generated by Django 5.2.7 on 2026-10-01 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0075_alter_spdvkpirecord_metric_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SPDVKpiDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('THE', 'Số lượng thẻ'), ('AGRIBANK_PLUS', 'Agribank Plus'), ('MOBILE_BANKING', 'Mobile Banking')], max_length=20, verbose_name='Chỉ tiêu')),
                ('year', models.IntegerField(verbose_name='Năm')),
                ('month', models.IntegerField(verbose_name='Tháng')),
                ('source', models.CharField(choices=[('CSP', 'Thẻ CSP'), ('VISA', 'Thẻ Visa'), ('EMOBILE', 'E-Mobile Banking'), ('SMS', 'SMS Banking')], max_length=10, verbose_name='Nguồn')),
                ('transaction_date', models.DateField(verbose_name='Ngày giao dịch')),
                ('customer_code', models.CharField(blank=True, max_length=50, verbose_name='Mã khách hàng')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spdv_kpi_details', to=settings.AUTH_USER_MODEL, verbose_name='Giao dịch viên')),
            ],
            options={
                'verbose_name': 'Chi tiết chỉ tiêu SPDV',
                'verbose_name_plural': 'Chi tiết chỉ tiêu SPDV',
                'ordering': ['-transaction_date'],
                'indexes': [models.Index(fields=['user', 'metric_type', 'year', 'month'], name='templates_a_user_id_8c91e4_idx')],
            },
        ),
    ]
