# Generated by Django 5.2.7 on 2026-10-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0076_spdvkpidetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='spdvkpidetail',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Số tài khoản'),
        ),
        migrations.AddField(
            model_name='spdvkpidetail',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Họ tên'),
        ),
    ]
