# Generated by Django 5.2.7 on 2026-10-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0077_spdvkpidetail_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spdvkpidetail',
            name='metric_type',
            field=models.CharField(choices=[('THE', 'Số lượng thẻ'), ('AGRIBANK_PLUS', 'Agribank Plus'), ('MOBILE_BANKING', 'Mobile Banking'), ('TK_PLUS', 'Tài khoản Plus'), ('OTT', 'Đăng ký OTT')], max_length=20, verbose_name='Chỉ tiêu'),
        ),
        migrations.AlterField(
            model_name='spdvkpirecord',
            name='metric_type',
            field=models.CharField(choices=[('THE', 'Số lượng thẻ'), ('AGRIBANK_PLUS', 'Agribank Plus'), ('MOBILE_BANKING', 'Mobile Banking'), ('TK_PLUS', 'Tài khoản Plus'), ('OTT', 'Đăng ký OTT')], max_length=20, verbose_name='Chỉ tiêu'),
        ),
        migrations.AlterField(
            model_name='spdvkpitarget',
            name='metric_type',
            field=models.CharField(choices=[('THE', 'Số lượng thẻ'), ('AGRIBANK_PLUS', 'Agribank Plus'), ('MOBILE_BANKING', 'Mobile Banking'), ('TK_PLUS', 'Tài khoản Plus'), ('OTT', 'Đăng ký OTT')], max_length=20, verbose_name='Chỉ tiêu'),
        ),
    ]
