# Generated by Django 5.2.7 on 2026-10-03 03:15

from django.db import migrations, models


def empty_to_null(apps, schema_editor):
    Business = apps.get_model('templates_app', 'Business')
    Business.objects.filter(so_gcn='').update(so_gcn=None)
    Business.objects.filter(ma_so_thue='').update(ma_so_thue=None)


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0078_alter_spdvkpidetail_metric_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='ma_so_thue',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Mã số thuế'),
        ),
        migrations.AlterField(
            model_name='business',
            name='so_gcn',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Số GCN đăng ký DN/Giấy ĐKKD/QĐ thành lập'),
        ),
        migrations.RunPython(empty_to_null, migrations.RunPython.noop),
    ]
