# Generated by Django 5.2.7 on 2026-10-03 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0079_business_gcn_mst_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='atmreplenishment',
            name='travel_order_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True, verbose_name='Số văn bản giấy đi đường'),
        ),
    ]
