# Generated by Django 5.2.7 on 2026-10-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0080_atmreplenishment_travel_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='atmreplenishment',
            name='travel_order_year',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Năm của số văn bản giấy đi đường'),
        ),
        migrations.AlterField(
            model_name='atmreplenishment',
            name='travel_order_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Số văn bản giấy đi đường'),
        ),
        migrations.AlterUniqueTogether(
            name='atmreplenishment',
            unique_together={('travel_order_year', 'travel_order_number')},
        ),
    ]
