# Generated by Django 5.2.7 on 2026-10-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0082_backfill_travel_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='unmatched_rows',
            field=models.JSONField(blank=True, default=list, verbose_name='Dòng file CSP/MSPH02 không khớp DPTB18'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nguồn thông tin đối tác'),
        ),
    ]
