# Generated by Django 5.2.7 on 2026-10-06 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0083_bank_statement_source_unmatched'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_key', models.CharField(max_length=50, verbose_name='Số TK (chuẩn hoá)')),
                ('bank_key', models.CharField(blank=True, max_length=100, verbose_name='Ngân hàng (chuẩn hoá)')),
                ('account_number', models.CharField(max_length=50, verbose_name='Số tài khoản')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Ngân hàng')),
                ('name', models.CharField(max_length=200, verbose_name='Tên chủ tài khoản')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lúc')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_names', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
            ],
            options={
                'verbose_name': 'Danh bạ tài khoản',
                'verbose_name_plural': 'Danh bạ tài khoản',
                'unique_together': {('account_key', 'bank_key')},
            },
        ),
    ]
