# Generated by Django 5.2.7 on 2025-12-11 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payroll_statistics", "0002_transaction"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="transaction",
            new_name="payroll_sta_transac_691697_idx",
            old_name="payroll_sta_transac_76d4e5_idx",
        ),
        migrations.RenameIndex(
            model_name="transaction",
            new_name="payroll_sta_transac_10a3dc_idx",
            old_name="payroll_sta_transac_a1b2c3_idx",
        ),
        migrations.RenameIndex(
            model_name="transaction",
            new_name="payroll_sta_unit_id_375eef_idx",
            old_name="payroll_sta_unit_id_d4e5f6_idx",
        ),
    ]
