# Generated by Django 5.2.7 on 2026-01-26 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Tiêu đề")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Mô tả"),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Hạn chót"),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Hoàn thành"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("normal", "Bình thường"), ("urgent", "Gấp")],
                        default="normal",
                        max_length=10,
                        verbose_name="Độ ưu tiên",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("monthly", "Tháng"),
                            ("quarterly", "Quý"),
                            ("ad_hoc", "Phát sinh"),
                        ],
                        default="ad_hoc",
                        max_length=15,
                        verbose_name="Phân loại",
                    ),
                ),
                (
                    "recurring_type",
                    models.CharField(
                        choices=[
                            ("none", "Không lặp"),
                            ("monthly", "Hàng tháng"),
                            ("quarterly", "Hàng quý"),
                        ],
                        default="none",
                        max_length=15,
                        verbose_name="Loại lặp",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ngày hoàn thành"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người tạo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Công việc",
                "verbose_name_plural": "Danh sách công việc",
                "ordering": ["-priority", "due_date", "-created_at"],
            },
        ),
    ]
