# Generated by Django 5.2.7 on 2026-08-02 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_assigned_to_alter_task_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='recurrence_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurrence_children', to='tasks.task', verbose_name='Sinh ra từ công việc'),
        ),
    ]
