# Generated by Django 5.2.7 on 2025-12-03 08:35

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Mã ngân hàng",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Tên ngân hàng"),
                ),
            ],
            options={
                "verbose_name": "Ngân hàng",
                "verbose_name_plural": "Ngân hàng",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="CompanyAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Số tài khoản"
                    ),
                ),
                (
                    "account_name",
                    models.CharField(max_length=200, verbose_name="Tên tài khoản"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang hoạt động"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="company_accounts",
                        to="salary.bank",
                        verbose_name="Ngân hàng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tài khoản công ty",
                "verbose_name_plural": "Tài khoản công ty",
                "ordering": ["account_number"],
            },
        ),
        migrations.CreateModel(
            name="ProcessingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255, verbose_name="Tên file")),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("PAYROLL", "Chi trả lương"),
                            ("COLLECTION", "Thu hộ"),
                        ],
                        max_length=20,
                        verbose_name="Loại giao dịch",
                    ),
                ),
                (
                    "total_records",
                    models.IntegerField(default=0, verbose_name="Tổng số bản ghi"),
                ),
                (
                    "successful_records",
                    models.IntegerField(
                        default=0, verbose_name="Số bản ghi thành công"
                    ),
                ),
                (
                    "failed_records",
                    models.IntegerField(default=0, verbose_name="Số bản ghi lỗi"),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Tổng số tiền",
                    ),
                ),
                (
                    "duplicate_accounts",
                    models.TextField(
                        blank=True,
                        help_text="Danh sách STK trùng lặp, ngăn cách bởi dấu phẩy",
                        verbose_name="Tài khoản trùng lặp",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Thành công"),
                            ("ERROR", "Lỗi"),
                            ("PARTIAL", "Một phần"),
                        ],
                        default="SUCCESS",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Thông báo lỗi"),
                ),
                (
                    "output_file",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="File đầu ra"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Thời gian xử lý"
                    ),
                ),
                (
                    "company_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processing_histories",
                        to="salary.companyaccount",
                        verbose_name="Tài khoản công ty",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="salary_processings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người xử lý",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lịch sử xử lý",
                "verbose_name_plural": "Lịch sử xử lý",
                "ordering": ["-processed_at"],
            },
        ),
        migrations.CreateModel(
            name="Beneficiary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="Họ và tên"),
                ),
                (
                    "account_number",
                    models.CharField(max_length=50, verbose_name="Số tài khoản"),
                ),
                (
                    "bank_code",
                    models.CharField(
                        blank=True,
                        help_text="Mã ngân hàng từ file import",
                        max_length=20,
                        verbose_name="Mã ngân hàng",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Ghi chú")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "bank",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="beneficiaries",
                        to="salary.bank",
                        verbose_name="Ngân hàng",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="beneficiaries",
                        to="salary.companyaccount",
                        verbose_name="Công ty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Người thụ hưởng",
                "verbose_name_plural": "Người thụ hưởng",
                "ordering": ["full_name"],
                "unique_together": {("account_number", "bank_code")},
            },
        ),
    ]
